### ISSUE TITLE
Failed to create task or type PCTConnection

### ISSUE THREAD

**Issue by schnitty** [Riverside-Software/pct#112]
I am going through the quick start in your documentation and the build is failing on step 2.
Here is the full output from the command line:

```
C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject>ant -v
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
Trying the default build file: build.xml
Buildfile: C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject\build.xml
Detected Java version: 1.8 in: C:\Progra~1\Java\jdk1.8.0_60\jre
Detected OS: Windows 7
parsing buildfile C:\Users\Administrator\Progress\Developer Studio 4.3.1
\workspace\MyProject\build.xml with URI = file:/C:/Users/Administrator/Progress/Develope
r%20Studio%204.3.1/workspace/MyProject/build.xml
Project base dir set to: C:\Users\Administrator\Progress\Developer Studio 4.3.1
\workspace\MyProject
parsing buildfile jar:file:/C:/apache-ant-1.9.6/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI =  
jar:file:/C:/apache-ant-1.9.6/lib/ant.jar!/org/apache/to
ols/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Property "env.PCT_HOME" has not been set
dropping C:\Users\Administrator\Progress\Developer Studio 4.3.1   
\workspace\MyProject\${env.PCT_HOME}\lib\PCT.jar from path as it doesn't exist
Build sequence for target(s) `build' is [build]
Complete build sequence is [build, ]

build:
[PCTVersion] PCT Version 1.1-pre - Build 194
[ProgressVersion] dlcHome attribute not set. Falling back to DLC environment variable :    
c:\progress\v115
[ProgressVersion] OpenEdge version found : OpenEdge Release 11.5.1 as of Wed May  6 19:01:46 EDT 2015
[ProgressVersion] Using object : com.phenix.pct.ProgressV114
[PCTCreateBase] OpenEdge version found : OpenEdge Release 11.5.1 as of Wed May  6 
19:01:46 EDT 2015
[PCTCreateBase] Using object : com.phenix.pct.ProgressV114
[PCTCreateBase] Copying empty DB to db
[PCTCreateBase] Current OS is Windows 7
[PCTCreateBase] Output redirected to C:\Users\Administrator\Progress\Developer Studio 4.3.
\workspace\MyProject\db\db.procopy.log
[PCTCreateBase] Setting environment variable: DLC=c:\progress\v115
[PCTCreateBase] Executing 'c:\progress\v115\bin\_dbutil.exe' with arguments:    
[PCTCreateBase] 'procopy'
[PCTCreateBase] 'c:\progress\v115\empty8'
[PCTCreateBase] 'db'
[PCTCreateBase]
[PCTCreateBase] The ' characters around the executable and arguments are
[PCTCreateBase] not part of the command.
[PCTCreateBase] OpenEdge version found : OpenEdge Release 11.5.1 as of Wed May  6
19:01:46 EDT 2015
[PCTCreateBase] Using object : com.phenix.pct.ProgressV114
[PCTCreateBase] cpstream is not defined. You may have problems if file names have characters
outside of ASCII range. You really should define it !
[PCTCreateBase] Current OS is Windows 7
[PCTCreateBase] Setting environment variable: DLC=c:\progress\v115
[PCTCreateBase] Executing 'c:\progress\v115\bin\_progres.exe' with arguments:
[PCTCreateBase] '-b'
[PCTCreateBase] '-q'
[PCTCreateBase] '-p'
[PCTCreateBase] 'C:\Users\SCHNEI~1\AppData\Local\Temp\pctinit29301.p'
[PCTCreateBase]
[PCTCreateBase] The ' characters around the executable and arguments are
[PCTCreateBase] not part of the command.
[PCTCreateBase] Loading C:\Users\Administrator\Progress\Developer Studio 4.3.
\workspace\MyProject\db\db.df in database
[mkdir] Skipping C:\Users\Administrator\Progress\Developer Studio 4.3.
\workspace\MyProject\build because it already exists.

BUILD FAILED
C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject\build.xml:13: 
Problem: failed to create task or type PCTConnection
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

    at org.apache.tools.ant.UnknownElement.getNotFoundException(UnknownElement.java:500)
    at org.apache.tools.ant.UnknownElement.makeObject(UnknownElement.java:432)
    at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:164)
    at org.apache.tools.ant.Task.perform(Task.java:347)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.Main.runBuild(Main.java:853)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 1 second

C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject>
```

I got through step 1 ok but connecting to the database before building doesn't seem to be working for me.

The db.lg and db.procopy files seem to indicate that the database was created ok.  I can provide if necessary.

I am new to Progress OpenEdge and Developer Studio so please go easy on me if I am missed something silly.

I have been following the QuickStart and have been copying and pasting from that so there shouldn't be any issues with the build.xml or .p or .df files.  I can of course provide those if necessary.

**Comment by jakejustus** [comment]
Hi,

You may want to add `<typedef resource="types.properties" />` after the `<taskdef>` node.
That's written in the InstallDocumentation page, but not in the QuickStart page, I'll update this part.

Gilles

**Comment by schnitty** [comment]
Thanks jakejustus that got me past that problem.  Unfortunately now I have another one :(
When I try to build this is now what I get:

```
C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject>ant -v
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
Trying the default build file: build.xml
Buildfile: C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject\build.xml
Detected Java version: 1.8 in: C:\Progra~1\Java\jdk1.8.0_60\jre
Detected OS: Windows 7
parsing buildfile C:\Users\Administrator\Progress\Developer Studio 4.3.1    
\workspace\MyProject\build.xml with URI = file:/C:/Users/Administrator/Progress/Develope
r%20Studio%204.3.1/workspace/MyProject/build.xml
Project base dir set to: C:\Users\Administrator\Progress\Developer Studio 4.3.1   
\workspace\MyProject
parsing buildfile jar:file:/C:/apache-ant-1.9.6/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = 
jar:file:/C:/apache-ant-1.9.6/lib/ant.jar!/org/apache/to
ols/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Build sequence for target(s) `build' is [build]
Complete build sequence is [build, ]

build:
[PCTVersion] PCT Version 1.1-pre - Build 194
[ProgressVersion] dlcHome attribute not set. Falling back to DLC environment variable :     
c:\progress\v115
[ProgressVersion] OpenEdge version found : OpenEdge Release 11.5.1 as of Wed May  6    
19:01:46 EDT 2015
[ProgressVersion] Using object : com.phenix.pct.ProgressV114
[PCTCreateBase] OpenEdge version found : OpenEdge Release 11.5.1 as of Wed May  6    
19:01:46 EDT 2015
[PCTCreateBase] Using object : com.phenix.pct.ProgressV114
[PCTCreateBase] Database db already exists
[mkdir] Skipping C:\Users\Administrator\Progress\Developer Studio 4.3.1  
\workspace\MyProject\build because it already exists.
[PCTCompile] OpenEdge version found : OpenEdge Release 11.5.1 as of Wed May  6 19:01:46   
EDT 2015
[PCTCompile] Using object : com.phenix.pct.ProgressV114
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] cpstream is not defined. You may have problems if file names have characters    
outside of ASCII range. You really should define it !
[PCTCompile] Current OS is Windows 7
[PCTCompile] Setting environment variable: DLC=c:\progress\v115
[PCTCompile] Executing 'c:\progress\v115\bin\_progres.exe' with arguments:
[PCTCompile] '-b'
[PCTCompile] '-q'
[PCTCompile] '-param'
[PCTCompile] 'C:\Users\SCHNEI~1\AppData\Local\Temp\pct_params20161.txt'
[PCTCompile] '-p'
[PCTCompile] 'C:\Users\SCHNEI~1\AppData\Local\Temp\pctinit41160.p'
[PCTCompile]
[PCTCompile] The ' characters around the executable and arguments are
[PCTCompile] not part of the command.
[PCTCompile] PROPATH : C:\Users\SCHNEI~1 
\AppData\Local\Temp\pct36016.pl,.,c:\progress\v115\tty,c:\progress\v115   
\tty\ablunit.pl,c:\progress\v115\tty\adecomm.pl,c
:\progress\v115\tty\adecomp.pl,c:\progress\v115\tty\adeedit.pl,c:\progress\v115  
\tty\adeshar.pl,c:\progress\v115\tty\dataadmin.pl,c:\progress\v115\tty\OpenEdge.B
 usinessLogic.pl,c:\progress\v115\tty\OpenEdge.Core.pl,c:\progress\v115 
\tty\OpenEdge.ServerAdmin.pl,c:\progress\v115\tty\prodict.pl,c:\progress\v115,c:\progress\
v115\bin
 [PCTCompile] RUN pct/v11/pctCompile.p
 [PCTCompile] Switching to fileset C:\Users\Administrator\Progress\Developer Studio 4.3.1
 \workspace\MyProject\src
 [PCTCompile] Compiling test2.p in directory C:\Users\Administrator\Progress\Developer Studio    
4.3.1\workspace\MyProject\src TO C:\Users\Administrator\Progress\De
veloper Studio 4.3.1\workspace\MyProject\build/
[PCTCompile] Error compiling file C:\Users\Administrator\Progress\Developer Studio 4.3.1  
\workspace\MyProject\src\test2.p at line 1 column 8
[PCTCompile] CREATE MyTable.
[PCTCompile] -------^
[PCTCompile] Unknown or ambiguous table MyTable. (725)
[PCTCompile] ** C:\Users\Administrator\Progress\Developer Studio 4.3.1  
\workspace\MyProject\src\test2.p Could not understand line 1. (196)
[PCTCompile] ** Unknown table name MyTable. (200)
[PCTCompile] ** C:\Users\Administrator\Progress\Developer Studio 4.3.1  
\workspace\MyProject\src\test2.p Could not understand line 2. (196)
[PCTCompile]
[PCTCompile] 0 file(s) compiled
[PCTCompile] Failed to compile  1  file(s)
[PCTCompile] Return value : 10

BUILD FAILED
C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject\build.xml:15: Return 
code : 10
    at com.phenix.pct.PCTRun.execute(PCTRun.java:739)
    at com.phenix.pct.PCTCompile.execute(PCTCompile.java:683)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.Main.runBuild(Main.java:853)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

 Total time: 0 seconds

 C:\Users\Administrator\Progress\Developer Studio 4.3.1\workspace\MyProject>
```

I have opened the database using Data Administrator and have run the code in test2.p in data administrator and it all works fine.  It would seem that in the build it isn't finding/connecting to the database properly for the code in test.p to compile properly.  The problem is that because I am a noob in OpenEdge and ant builds and PCT I'm not sure what the problem is or how to fix it.  Any help would be appreciated.  Thanks.

**Comment by schnitty** [comment]
I managed to figure it out.  I had the PCTConnection element outside (above) the PCTCompile element.  I moved the PCTConnection to be a child element of PCTCompile and now everything is ok.

**Comment by jakejustus** [comment]
Quickstart page has been updated. Closing issue, please open a new one if you have additional issues.
