### ISSUE TITLE
PCTCompile DestDir - NullPointerExpcetion

### ISSUE THREAD

**Issue by paulmowat** [Riverside-Software/pct#149]
Hi,

If I set the PCTCompile destDir to a path such as 

/DevelopmentOE/application/compiled/version1/OE10

Where I have the folder structure already created down to /DevelopmentOE/application/compiled I get a java.lang.NullPointerException exception. I was expecting it to create the folders structure as required i.e. version1/OE10.

I can probably deal with it with a mkdir but would be nice if the compile handled it and created the subfolders as required.

Thanks

Paul

**Comment by jakejustus** [comment]
Do you have the full stacktrace, as well as the PCT version number ?
I had a quick look at my current version, and PCTCompile is using mkdirs(), which should create the parent directories.

**Comment by paulmowat** [comment]
Hi,

I'm using PCT-202 and the stack trace I'm getting from Jenkins is as below.

```
14:21:33 [op8oe102bprogress] C:\BuildServer\Applications\Jenkins\workspace\OP - Trunk Pipeline Test\trunk\Build\build.xml:685: The following error occurred while executing this line:
14:21:33 [op8oe102bprogress] C:\BuildServer\Applications\Jenkins\workspace\OP - Trunk Pipeline Test\trunk\Build\build.xml:701: The following error occurred while executing this line:
14:21:33 [op8oe102bprogress] C:\BuildServer\Applications\Jenkins\workspace\OP - Trunk Pipeline Test\trunk\Build\build.xml:935: java.lang.NullPointerException
14:21:33 [op8oe102bprogress]    at com.phenix.pct.PCTBgRun.cleanup(PCTBgRun.java:537)
14:21:33 [op8oe102bprogress]    at com.phenix.pct.PCTBgCompile.execute(PCTBgCompile.java:355)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
14:21:33 [op8oe102bprogress]    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
14:21:33 [op8oe102bprogress]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:33 [op8oe102bprogress]    at java.lang.reflect.Method.invoke(Method.java:498)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Task.perform(Task.java:348)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Target.execute(Target.java:435)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Target.performTasks(Target.java:456)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
14:21:33 [op8oe102bprogress]    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
14:21:33 [op8oe102bprogress]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:33 [op8oe102bprogress]    at java.lang.reflect.Method.invoke(Method.java:498)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Task.perform(Task.java:348)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Target.execute(Target.java:435)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Target.performTasks(Target.java:456)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
14:21:33 [op8oe102bprogress]    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
14:21:33 [op8oe102bprogress]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:33 [op8oe102bprogress]    at java.lang.reflect.Method.invoke(Method.java:498)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Task.perform(Task.java:348)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
14:21:33 [op8oe102bprogress]    at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
14:21:33 [op8oe102bprogress]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:21:33 [op8oe102bprogress]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:21:33 [op8oe102bprogress]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:33 [op8oe102bprogress]    at java.lang.reflect.Method.invoke(Method.java:498)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
14:21:33 [op8oe102bprogress]    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
14:21:33 [op8oe102bprogress]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:33 [op8oe102bprogress]    at java.lang.reflect.Method.invoke(Method.java:498)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Task.perform(Task.java:348)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Target.execute(Target.java:435)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Target.performTasks(Target.java:456)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Main.runBuild(Main.java:854)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.Main.startAnt(Main.java:236)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
14:21:33 [op8oe102bprogress]    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
14:21:33 [op8oe102bprogress]
```

From PDSOE I just get the java.lang.NullPointerException. The only thing i changed from a build that was working was to move into a subfolder.

/DevelopmentOE/application/compiled/OE10

was changed to 

/DevelopmentOE/application/compiled/version1/OE10

Thanks

Paul

**Comment by paulmowat** [comment]
Sorry about the formatting of the stack trace. Can't seem to get it neater.

**Comment by jakejustus** [comment]
That's from PCTBgCompile, a quick look confirms that it doesn't use mkdirs() but mkdir(), so not creating required parent directories. Will try to fix it soon.

**Comment by paulmowat** [comment]
Brilliant thanks, for some more info.

PCTCompile gives me Unable to create destDir

```
<PCTCompile basedir="trunk/OpenPeople" destDir="compile/OP9-102B-Progress" dlcHome="C:/Progress/OE102B">

        <fileset dir="trunk/OpenPeople" casesensitive="false">
          <include name="gcpay/p/test.p" />         
        </fileset>

      </PCTCompile>
```

PCTCompileExt gives me java.lang.NullPointerException

```
<PCTCompileExt basedir="trunk/OpenPeople" destDir="compile/OP9-102B-Progress" dlcHome="C:/Progress/OE102B">

        <fileset dir="trunk/OpenPeople" casesensitive="false">
          <include name="gcpay/p/test.p" />         
        </fileset>

      </PCTCompileExt>
```

**Comment by jakejustus** [comment]
Fixed in dev - Will be available in next version
