### ISSUE TITLE
javax.xml.bind.JAXBException: "eu.rssw.rcode" doesnt contain ObjectFactory.class

### ISSUE THREAD

**Issue by ghost** [Riverside-Software/pct#165]
Java exception when generating auto-documentation under Jenkins, with ConsultingWerk's tools.

The crash is reproduced on Linux and on Windows (JRE 1.7 x64 for Linux, JRE 1.8.0_92 for Windows).

No error when lauching the same Ant-Script with Eclipse/OpenEdge Studio (OE11.6, JRE , java 1.8.0_91)...

Ant-Script:

```
    <target name="Dokumentation" depends ="taskdef" description="Erzeugt die Dokumentation">          
        <PCTVersion/>

        <ClassDocumentation destDir="docs/classdoc" dlcHome="${DLC_HOME}">
            <fileset dir="${workspace.dir}/OSIV3G/docs/preprocessed" includes="**/*.cls" />
            <propath>
                <pathelement location="${workspace.dir}/OSIV3G/docs/preprocessed" />
            </propath>
        </ClassDocumentation>

        <echo message="Generating HTML Class Documentation" />

        <PCTRun
            procedure="Consultingwerk/Studio/ClassDocumentation/generate-class-reference.p"
            graphicalMode="false" dlcHome="${DLC_HOME}" cpinternal="iso8859-1" cpstream="iso8859-1" 
            compileUnderscore="true" inputchars="16000" 
            token="4000" TTBufferSize="100000">

            <propath>
                <pathelement path="${main.dir}/Backend"/>
                <pathelement path="${workspace.dir}/OscFramework" />
                <pathelement path="${workspace.dir}/OSIV3G/lib"/>
                <pathelement path="${workspace.dir}/OscFramework/${build.dir}/OscFramework.pl"/>
                <pathelement path="${workspace.dir}/SmartComponentLibrary/${build.dir}/SmartComponentLibrary.pl" />
                <pathelement path="${workspace.dir}/SmartComponentLibrary/${build.dir}/SmartComponentLibrary.pl/src" />
                <pathelement path="${workspace.dir}/SmartComponentLibrary/${build.dir}/SmartComponentLibrary.pl/OERA" />
                <pathelement path="${workspace.dir}/SmartComponentLibrary" />
                <pathelement path="${workspace.dir}/SmartComponentLibrary/src" />
                <pathelement path="${workspace.dir}/SmartComponentLibrary/OERA" />                                          
                <pathelement path="${DLC_HOME}/tty/netlib/OpenEdge.Net.pl" />                       
            </propath>

            <DBConnection dbName="${smartdb.dir}" hostname="${smartHost}" dbPort="${smartPort}" Protocol="TCP" />       

            <Parameter name="TargetDir" value="${workspace.dir}/OSIV3G/docs/Documentation" />
            <Parameter name="SourceDir" value="${workspace.dir}/OSIV3G/docs/classdoc" />
            <Parameter name="TemplateSourceDir" value="${workspace.dir}/OscFramework/Osc/Templates/ClassReference"/>
            <Parameter name="ResourceDir" value="${workspace.dir}/OscFramework/Osc/Templates/ClassReference/Resources"/>
            <Parameter name="Services" value="${workspace.dir}/SmartComponentLibrary/Consultingwerk/Studio/SmartDox/class-doc-services.xml"/>
            <Parameter name="OpenEdgeDocFileName" value="${workspace.dir}/SmartComponentLibrary/Consultingwerk/Studio/OpenEdgeDocs/${consultingwerk.DlcVersion}.xml"/>       
            <Parameter name="OpenEdgeBaseLink" value="http://help.consultingwerkcloud.com/openedge/${consultingwerk.DlcVersion}/"/>

            <Parameter name="PreloadClasses" value="true"/>  
            <Parameter name="GenerateTreeViewOverview" value="true"/>          
        </PCTRun>

```

Exception:

```
Building in workspace /data/JenkinsWorkspace/OSIV3G/OSIV3G
[OSIV3G] $ ant -file build4Linux.xml -Dtempdir=/data/temp/.pct -Dfirstparam=/data/JenkinsWorkspace/OSIV3G -Dhostname=svr-de-windows.ivnet.ch -Ddlc=/usr/dlc -DdbPort=4748 -DsmartDB=smartdb Dokumentation
Unable to locate tools.jar. Expected to find it in /usr/lib64/jvm/java-1.7.1-ibm-1.7.1/lib/tools.jar
Buildfile: build4Linux.xml

taskdef:

Dokumentation:
[PCTVersion] PCT Version : jenkins-QA-PCT-206
[ClassDocumentation] Generating XML documentation (11.5+ method)

BUILD FAILED
javax.xml.bind.JAXBException: Provider com.sun.xml.internal.bind.v2.ContextFactory could not be instantiated: javax.xml.bind.JAXBException: "eu.rssw.rcode" doesnt contain ObjectFactory.class or jaxb.index
 - with linked exception:
[javax.xml.bind.JAXBException: "eu.rssw.rcode" doesnt contain ObjectFactory.class or jaxb.index]
    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:158)
    at javax.xml.bind.ContextFinder.find(ContextFinder.java:359)
    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:443)
    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:406)
    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:310)
    at eu.rssw.rcode.ClassCompilationUnit.classToXML(ClassCompilationUnit.java:48)
    at eu.rssw.pct.oedoc.ClassDocumentationVisitor.toXML(ClassDocumentationVisitor.java:57)
    at eu.rssw.pct.oedoc.OpenEdgeDocumentation115.execute(OpenEdgeDocumentation115.java:198)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
    at java.lang.reflect.Method.invoke(Method.java:620)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:357)
    at org.apache.tools.ant.Target.performTasks(Target.java:385)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
    at org.apache.tools.ant.Main.runBuild(Main.java:758)
    at org.apache.tools.ant.Main.startAnt(Main.java:217)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
Caused by: javax.xml.bind.JAXBException: "eu.rssw.rcode" doesnt contain ObjectFactory.class or jaxb.index
    at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:229)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
    at java.lang.reflect.Method.invoke(Method.java:620)
    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:184)
    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:144)
    ... 23 more
```

```
```

**Comment by jakejustus** [comment]
Could you verify that you have only a single version of PCT.jar in your classpath or in the $ANT_HOME/lib directory ?
I'm not able to reproduce the problem for now, and unit tests on both Windows and Linux are running correctly (with Oracle JRE).

**Comment by ghost** [comment]
I've only ont PCT.jar in my project.
I've tryed to launch it with the jre from Progress and the result is the same.
But the same script launched directly in Eclipse is running well !
PS: I'm using OE11.6.**2**

**Comment by jakejustus** [comment]
As seen offline, using `-lib /path/to/ast.jar` instead of nested pathelement in taskdef solved the issue.

**Comment by ghost** [comment]
Hi Gilles,

It’s working now on Windows, but I’ve problems under Linux:

```
ant -file build4Linux.xml -Dtempdir=/data/temp/.pct -Dfirstparam=/data/JenkinsWorkspace/OSIV3G -Dhostname=svr-de-windows.ivnet.ch -Ddlc=/usr/dlc -DdbPort=4748 -DsmartDB=smartdb Dokumentation -lib lib/PCT.jar -lib lib/ast.jar -lib lib/ast-dependencies.jar -lib lib/abldoc-core.jar -lib lib/ablservice.jar -lib /lib/ablunit.jar
Unable to locate tools.jar. Expected to find it in /usr/lib64/jvm/java-1.7.1-ibm-1.7.1/lib/tools.jar
Buildfile: build4Linux.xml

BUILD FAILED
/data/JenkinsWorkspace/OSIV3G/OSIV3G/build4Linux.xml:44: taskdef A class needed by class eu.rssw.pct.oedoc.OpenEdgeDocumentation115 cannot be found: org.eclipse.core.runtime.IPath
```
Something is missing, but I dont see what…

My build.xml file contains:
```
…
<taskdef resource="PCT.properties" classpath="lib/PCT.jar"/>
<typedef resource="types.properties" classpath="lib/PCT.jar" />
<taskdef resource="extras115.properties" classpath="lib/PCT.jar"/>
…

<target name="Dokumentation" depends ="taskdef" description="Erzeugt die Dokumentation">
  <PCTVersion/>
  <ClassDocumentation destDir="docs/classdoc" dlcHome="${DLC_HOME}">
    <fileset dir="${workspace.dir}/OSIV3G/docs/preprocessed" includes="**/*.cls" />
    <propath>
      <pathelement location="${workspace.dir}/OSIV3G/docs/preprocessed" />
    </propath>
  </ClassDocumentation>
</target>
```

**Comment by sdobbey** [comment]
The above issue in linux seems to work when PCT.jar is added in -lib  parameter of ant command.

**Comment by gquerret** [comment]
For future reference, this issue is fixed in v209 which doesn't rely on jaxb.index anymore.
