### ISSUE TITLE
Confusion using the DBConnectionSet from the example.  Could not load definitions from resource types.properties.

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#169]
Here's the xml I've put together from the example:

``` xml
<taskdef resource="PCT.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" />

<!-- build all database connections -->
<typedef resource="types.properties" />
<DBConnectionSet id="alldbs">
  <DBConnection paramFile="${localdbpf}" LogicalName="${logicaldbname}" singleUser="yes" ReadOnly="yes" >
    <Alias name="lname" />
    <Alias name="ldb" />
    <Alias name="baldb" />
    <Alias name="tqldb" />
    <Alias name="trend" />
    <Alias name="xlatedb" />
  </DBConnection>
  <DBConnection paramFile="${localdbwipf}" LogicalName="${logicaldbwiname}" singleUser="yes" ReadOnly="yes" >
    <Alias name="widb" />
    <Alias name="nxtwi" />
  </DBConnection>
</DBConnectionSet>
```

Clearly, I'm missing something obvious.

The following errors appear:

```
C:\nxtsx103\build>ant winonly-build
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=temp
Buildfile: C:\nxtsx103\build\build.xml
  [typedef] Could not load definitions from resource types.properties. It could not be found.

BUILD FAILED
C:\nxtsx103\build\build.xml:69: Problem: failed to create task or type DBConnectionSet
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
```

**Comment by jakejustus** [comment]
From a quick look, I'd say that you need the classpath attribute in the typedef node (as in taskdef node).

**Comment by wilddoug** [comment]
ok - excellent!

``` xml
<taskdef resource="PCT.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" />

<!-- build all database connections -->
<typedef resource="types.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" />
```

That does get past that error, which is excellent.

However, when I attempt to use the set in a PCTCompile task, I get an error.
The line in my build.xml:
`<DBConnectionSet refid="infor" />`

The error:

```
[PCTCompile] Using object : com.phenix.pct.ProgressV114
[PCTCompile] PCTCompile - Progress Code Compiler
Class com.phenix.pct.DBConnectionSet (loaded via AntClassLoader[C:\nxtsx103\build\PCT\v206\lib\PCT.jar]) is not a subclass of com.phenix.pct.DBConnectionSet (loaded via AntClassLoader[C:\nxtsx103\build\PCT\v206\lib\PCT.jar])

BUILD FAILED
C:\nxtsx103\build\build.xml:421: alldbs doesn't denote a DBConnectionSet
        at org.apache.tools.ant.types.DataType.getCheckedRef(DataType.java:256)
        at org.apache.tools.ant.types.DataType.getCheckedRef(DataType.java:214)
        at org.apache.tools.ant.types.DataType.getCheckedRef(DataType.java:202)
        at com.phenix.pct.DBConnectionSet.getRef(DBConnectionSet.java:43)
        at com.phenix.pct.DBConnectionSet.getDBConnections(DBConnectionSet.java:56)
        at com.phenix.pct.GenericExecuteOptions.getAllDbConnections(GenericExecuteOptions.java:642)
        at com.phenix.pct.PCTRun.createInitProcedure(PCTRun.java:686)
        at com.phenix.pct.PCTRun.execute(PCTRun.java:386)
        at com.phenix.pct.PCTCompile.execute(PCTCompile.java:361)
        at com.phenix.pct.CompilationWrapper.execute(CompilationWrapper.java:43)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

```

I appreciate all the help!

**Comment by wilddoug** [comment]
Also tried:

``` xml
<!-- build all database connections -->
<typedef resource="types.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" />
<DBConnection id="maindb" paramFile="config/maindb.pf" logicalName="maindb" >
  <Alias name="lname" />
  <Alias name="ldb" />
  <Alias name="baldb" />
  <Alias name="tqldb" />
  <Alias name="trend" />
  <Alias name="xlatedb" />
</DBConnection>
<DBConnection id="widb" paramFile="config/widb.pf" logicalName="widb" />

<DBConnectionSet id="alldbs">
  <DBConnection refid="maindb" singleUser="no" readOnly="yes" />
  <DBConnection refid="widb"   singleUser="no" readOnly="yes" />
</DBConnectionSet>
```

When I attempt this in a PCTRun task using id=

``` xml
    <DBConnectionSet id="alldbs" />
```

It doesn't seem to be putting the databases on the command line, or in a pf file...

```
   [PCTRun] RUN ./tasksrc/correct_XL_data.p
   [PCTRun] Unknown or ambiguous table xl_instance. (725)
```

**Comment by jakejustus** [comment]
Try the loaderRef attribute of <taskdef>

**Comment by jakejustus** [comment]
Documentation should have been updated a while ago, but it doesn't seem to
be the case :-(

Envoyé de mon téléphone

**Comment by wilddoug** [comment]
I think I'm past the typedef issue at this point, with this line:

``` xml
<typedef resource="types.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" />
```

I'm now having issues implementing the DBConnection and DBConnectionSet. No errors appear, but also no databases connections are made.

Thanks!

**Comment by jakejustus** [comment]
Not easy to send links using my phone, but you have to add loaderRef
attribute to both taskdef and typedef so that they are loaded with the same
class loader.

Envoyé de mon téléphone

**Comment by wilddoug** [comment]
I sincerely apologize, but I'm not sure what to change the xml to.  This is not an emergency, and I've done some googling on typedef and loaderRef, but it hasn't sunk into my brain yet.
Any working examples of DBConnectionSet would be appreciated.

**Comment by gquerret** [comment]
> I sincerely apologize, but I'm not sure what to change the xml to. This is not an emergency, and I've done some googling on typedef and loaderRef, but it hasn't sunk into my brain yet.

Time for a remote consulting session. Or on-site if you're in a sunny location :-)

When PCT.jar is not in `$ANT_HOME/lib` or in the `-lib` command line option, but specified in the classpath attribute of typedef and taskdef, then you have to use the loaderRef attribute in both tasks in order to have Ant use the same classloader. Otherwise, it will fail with this ridiculous error message :

```
Class com.phenix.pct.DBConnectionSet (loaded via AntClassLoader[C:\nxtsx103\build\PCT\v206\lib\PCT.jar]) is not a subclass of com.phenix.pct.DBConnectionSet (loaded via AntClassLoader[C:\nxtsx103\build\PCT\v206\lib\PCT.jar])
```

So use this declaration :

``` xml
<taskdef resource="PCT.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" loaderRef="pct" />
<typedef resource="types.properties" classpath="${env.PCT_HOME}/lib/PCT.jar" loaderRef="pct" />
```

**Comment by wilddoug** [comment]
The last two lines of the email were what I really needed to move forward -
it wasn't clear from the emails or examples what was needed.
Attached is a working build.xml example of how to use the DBConnection and
DBConnectionSet, if you'd like to update your documentation example.

Thanks again for your time and this amazing product!
