### ISSUE TITLE
PCTRun with invalid ini file parameter causes exception

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/pct#185]
Caused by the ini file name parameter pointing to an invalid file name. 

```
[PCTVersion] PCT Version : jenkins-QA-PCT-206
 
BUILD FAILED
C:\enterprise\product\shelves\stara\SmartComponentLibrary\build.xml:50: java.lang.NullPointerException
        at com.phenix.pct.GenericExecuteOptions.setIniFile(GenericExecuteOptions.java:181)
        at com.phenix.pct.CompilationWrapper.setIniFile(CompilationWrapper.java:351)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.IntrospectionHelper$7.set(IntrospectionHelper.java:1115)
        at org.apache.tools.ant.IntrospectionHelper$AttributeSetter.setObject(IntrospectionHelper.java:1510)
        at org.apache.tools.ant.IntrospectionHelper.setAttribute(IntrospectionHelper.java:411)
        at org.apache.tools.ant.RuntimeConfigurable.maybeConfigure(RuntimeConfigurable.java:527)
        at org.apache.tools.ant.RuntimeConfigurable.maybeConfigure(RuntimeConfigurable.java:463)
        at org.apache.tools.ant.Task.maybeConfigure(Task.java:202)
        at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:200)
        at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:164)
        at org.apache.tools.ant.Task.perform(Task.java:347)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
 
Total time: 1 minute 29 seconds
 ```

**Comment by gquerret** [comment]
Reproduced, will take care of that a bit later.

**Comment by gquerret** [comment]
Fixed in master
