### ISSUE TITLE
Unable to load imaging library in . Session is being terminated (16952)

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#249]
A thread is crashing on a windows build -- all versions are below.
```
     [echo] Operating system: Windows Server 2012, amd64, 6.2
     [echo] OpenEdge Release 11.6.3 as of Thu Sep  8 19:01:50 EDT 2016
     [echo] ANT Version : 1.9.9
[PCTVersion] PCT Version : pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa
```

After 10 enums are compiled, then 3939 class files are compiled, our build moves on the compiling all *.w files.
Only a few files get compiled, and this appears in the log when using 'ant -v':

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Trying to connect to : -pf c:\build\config\maindb.pf -ld nxt -1 -RO
[PCTCompile] Creating alias lname for database 1
[PCTCompile] Creating alias trend for database 1
[PCTCompile] Creating alias tqldb for database 1
[PCTCompile] Creating alias xlatedb for database 1
[PCTCompile] Creating alias baldb for database 1
[PCTCompile] Creating alias ldb for database 1
[PCTCompile] Trying to connect to : -pf c:\build\config\widb.pf -ld nxtwi -1 -RO
[PCTCompile] PROPATH : gui-code,gui-code\trend,gui-code\common,gui-code\enums,gui-code\twl,gui-code\twl\common,gui-code\twl\common\trigger,gui-code\twl\reports,gui-code\src,gui-code\dlc,gui-code\dlc\src,gui-code\dlc\trend,..\Progress\OpenEdge116\tty\netlib\OpenEdge.Net.pl,..\Progress\OpenEdge116\tty\OpenEdge.Core.pl,c:\build\temp\pct2607.pl,.,C:\Progress\OpenEdge116\gui,C:\Progress\OpenEdge116\gui\adecomm.pl,C:\Progress\OpenEdge116\gui\adecomp.pl,C:\Progress\OpenEdge116\gui\adedesk.pl,C:\Progress\OpenEdge116\gui\adedict.pl,C:\Progress\OpenEdge116\gui\adeedit.pl,C:\Progress\OpenEdge116\gui\adeicon.pl,C:\Progress\OpenEdge116\gui\aderes.pl,C:\Progress\OpenEdge116\gui\adeshar.pl,C:\Progress\OpenEdge116\gui\adeuib.pl,C:\Progress\OpenEdge116\gui\adeweb.pl,C:\Progress\OpenEdge116\gui\adexml.pl,C:\Progress\OpenEdge116\gui\dataadmin.pl,C:\Progress\OpenEdge116\gui\OpenEdge.BusinessLogic.pl,C:\Progress\OpenEdge116\gui\OpenEdge.Core.pl,C:\Progress\OpenEdge116\gui\OpenEdge.ServerAdmin.pl,C:\Progress\OpenEdge116\gui\prodict.pl,C:\Progress\OpenEdge116\gui\protools.pl,C:\Progress\OpenEdge116,C:\Progress\OpenEdge116\bin
[PCTCompile] RUN pct/pctCompile.p
[PCTCompile] Switching to fileset gui-code
[PCTCompile] Compiling analytics\v-analytics-inquiry.w in directory gui-code TO c:\build\gui-build\code
[PCTCompile] Compiling analytics\w-analytics-dashboard.w in directory gui-code TO c:\build\gui-build\code
[PCTCompile] Compiling analytics\w-analytics-report.w in directory gui-code TO c:\build\gui-build\code
[PCTCompile] Compiling ap\b-apebt-trans.w in directory gui-code TO c:\build\gui-build\code
[PCTCompile] Compiling ap\b-apee.w in directory gui-code TO c:\build\gui-build\code
[PCTCompile] Unable to load imaging library in . Session is being terminated. (16952)
[PCTCompile] Result: 2

BUILD FAILED

c:\build\build.xml:616: Progress procedure failed - Error reading return value
	at com.phenix.pct.PCTRun.execute(PCTRun.java:456)
	at com.phenix.pct.PCTCompile.execute(PCTCompile.java:347)
	at com.phenix.pct.CompilationWrapper.execute(CompilationWrapper.java:63)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: java.io.FileNotFoundException: temp\PCTResult53571.out (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.phenix.pct.PCTRun.execute(PCTRun.java:448)
	... 18 more
```

Any ideas what this might be?

**Comment by gquerret** [comment]
Any protrace or procore file ?

**Comment by wilddoug** [comment]
I think this was an environmental issue.  Had the user attempting the same build on a different machine and had no issues.  Going to assume it was a bad machine / bad OpenEdge install / bad hardware....
Closing the issue.
