### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#328]
### java.net.SocketException: Connection reset
When compiling ABL classes, after 60 files, we get this error. Have no idea why. It worked for years... Nothing new has been installed. We use PCTCompileExt (with Jenkins).

Have you seen anything like this in the past. We use one thread to compile the classes (so no multiple threads).

### Your environment
* Jenkins master: Windows Server 2008 R2 Standard
* Oracle Db is on a CentOS 7 Linux Distribution
* OpenEdge Release 11.6.2.006
* Ant version 1.9.4
* PCT version 1.3.1 (I know but haven't had the time yet to upgrade).

### Actual behaviour
When compiling ABL classes, after 60 files, we get this error. Have no idea why. It worked for years... Nothing new has been installed. We use PCTCompileExt (with Jenkins).

### Expected behaviour
Tell us what you think should happen

### Steps to reproduce
Don't know yet.

**Comment by gquerret** [comment]
PCT 1.3.1 ? Could you include the output of `<PCTVersion />` ?
I'd strongly recommend upgrading to the latest version. Issue #200 and #207 seem to be related to your proble.

**Comment by lievencardoen** [comment]
Hi Gilles, the PCT we use is like 4 years old... ;-) Sorry for that. I understand that an upgrade to the latest version is the way to go. So I've asked management to plan this.

Do you have any idea why this would happen? Maybe I can fix it in our version of PCT. Upgrading will need some work because we've changed a lot of PCT sources throughout the years. Especially to include translations.

Kind regards.

**Comment by gquerret** [comment]
The issue mentioned previously is about creating directories in PCTCompileExt, which could sometimes lead to an unknown OS-ERROR value.
Do you have any other stack trace in your log ?

**Comment by lievencardoen** [comment]
Java:

```
[echo] [PCTCompileExt] java.net.SocketException: Connection reset
[echo] [PCTCompileExt] at java.net.SocketInputStream.read(Unknown Source)
[echo] [PCTCompileExt] at java.net.SocketInputStream.read(Unknown Source)
[echo] [PCTCompileExt] at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
[echo] [PCTCompileExt] at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[echo] [PCTCompileExt] at sun.nio.cs.StreamDecoder.read(Unknown Source)
[echo] [PCTCompileExt] at java.io.InputStreamReader.read(Unknown Source)
[echo] [PCTCompileExt] at java.io.BufferedReader.fill(Unknown Source)
[echo] [PCTCompileExt] at java.io.BufferedReader.readLine(Unknown Source)
[echo] [PCTCompileExt] at java.io.BufferedReader.readLine(Unknown Source)
[echo] [PCTCompileExt] at com.phenix.pct.BackgroundWorker.listen(BackgroundWorker.java:104)
[echo] [PCTCompileExt] at com.phenix.pct.PCTBgRun$ListenerThread$1.run(PCTBgRun.java:592)
[echo] [PCTCompileExt] at java.lang.Thread.run(Unknown Source)
[echo] [PCTCompileExt] Result: -1073741819
```

The number -1073741819 is something strange. We've found articles online but I don't know if it has something to do with it...

https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_security-insiderplat_pc/file-system-error-1073741819-on-windows-10/30f76ed6-bac1-4863-bfc0-fddb746af898

https://borncity.com/win/2017/10/02/virtualbox-is-causing-file-system-error-1073741819/

Lieven

**Comment by lievencardoen** [comment]
In the dataserv.lg, when the exception occurs, there's also something strange. But I'm not a dataserver or oracle expert. There seems to be a logoff from dataserver, but why? (is there first the Java exception and then the logoff or vice versa...).

```
[18/11/22@16:27:50.028+0100] P-006336 T-002536 1 ORA -- OCI call OCIStmtExecute
[18/11/22@16:27:50.028+0100] P-006336 T-002536 1 ORA -- OCI call OCIStmtExecute
[18/11/22@16:27:50.030+0100] P-006336 T-002536 1 ORA -- OCI call omru
[18/11/22@16:27:50.031+0100] P-006336 T-002536 1 ORA -- OCI call OCIStmtExecute
[18/11/22@16:27:50.031+0100] P-006336 T-002536 1 ORA -- OCI call OCIStmtExecute
[18/11/22@16:27:50.036+0100] P-006336 T-002536 1 ORA -- OCI call omru
[18/11/22@16:27:50.522+0100] P-006336 T-002536 1 ORA -- Cursor oparse: 0 (0 kyr)
[18/11/22@16:27:50.523+0100] P-006336 T-002536 1 ORA -- Cursor oexec : 0 (0 kyr)
[18/11/22@16:27:50.525+0100] P-006336 T-002536 1 ORA -- Cursor oexfet: 0 (0 kyr)
[18/11/22@16:27:50.525+0100] P-006336 T-002536 1 ORA -- Cursor ofetch: 0 (0 kyr)
[18/11/22@16:27:50.526+0100] P-006336 T-002536 1 ORA -- Cursor ofen : 0 (0 kyr)
[18/11/22@16:27:50.526+0100] P-006336 T-002536 1 ORA -- Cursor obnd* : 0 (0 kyr)
[18/11/22@16:27:50.527+0100] P-006336 T-002536 1 ORA -- Cursor odefin: 0 (0 kyr)
[18/11/22@16:27:50.528+0100] P-006336 T-002536 1 ORA -- Cursor Rows processed 1 (last execution)
[18/11/22@16:27:50.529+0100] P-006336 T-002536 1 ORA -- Total Rows processed 637 (previous executions)
[18/11/22@16:27:50.529+0100] P-006336 T-002536 1 ORA -- OCI call OCIHandleFree
[18/11/22@16:27:50.530+0100] P-006336 T-002536 1 ORA -- Cursor oparse: 0 (0 kyr)
[18/11/22@16:27:50.531+0100] P-006336 T-002536 1 ORA -- Cursor oexec : 0 (0 kyr)
[18/11/22@16:27:50.532+0100] P-006336 T-002536 1 ORA -- Cursor oexfet: 0 (0 kyr)
[18/11/22@16:27:50.532+0100] P-006336 T-002536 1 ORA -- Cursor ofetch: 0 (0 kyr)
[18/11/22@16:27:50.533+0100] P-006336 T-002536 1 ORA -- Cursor ofen : 0 (0 kyr)
[18/11/22@16:27:50.533+0100] P-006336 T-002536 1 ORA -- Cursor obnd* : 0 (0 kyr)
[18/11/22@16:27:50.534+0100] P-006336 T-002536 1 ORA -- Cursor odefin: 0 (0 kyr)
[18/11/22@16:27:50.535+0100] P-006336 T-002536 1 ORA -- Cursor Rows processed 1 (last execution)
[18/11/22@16:27:50.535+0100] P-006336 T-002536 1 ORA -- Total Rows processed 637 (previous executions)
[18/11/22@16:27:50.536+0100] P-006336 T-002536 1 ORA -- OCI call OCIHandleFree
[18/11/22@16:27:50.537+0100] P-006336 T-002536 1 ORA -- Cursor oparse: 0 (0 kyr)
[18/11/22@16:27:50.538+0100] P-006336 T-002536 1 ORA -- Cursor oexec : 0 (0 kyr)
[18/11/22@16:27:50.539+0100] P-006336 T-002536 1 ORA -- Cursor oexfet: 0 (0 kyr)
[18/11/22@16:27:50.539+0100] P-006336 T-002536 1 ORA -- Cursor ofetch: 0 (0 kyr)
[18/11/22@16:27:50.540+0100] P-006336 T-002536 1 ORA -- Cursor ofen : 0 (0 kyr)
[18/11/22@16:27:50.540+0100] P-006336 T-002536 1 ORA -- Cursor obnd* : 0 (0 kyr)
[18/11/22@16:27:50.542+0100] P-006336 T-002536 1 ORA -- Cursor odefin: 0 (0 kyr)
[18/11/22@16:27:50.543+0100] P-006336 T-002536 1 ORA -- Cursor Rows processed 0 (last execution)
[18/11/22@16:27:50.543+0100] P-006336 T-002536 1 ORA -- OCI call OCIHandleFree
[18/11/22@16:27:50.545+0100] P-006336 T-002536 1 ORA -- Cursor oparse: 0 (0 kyr)
[18/11/22@16:27:50.545+0100] P-006336 T-002536 1 ORA -- Cursor oexec : 0 (0 kyr)
[18/11/22@16:27:50.546+0100] P-006336 T-002536 1 ORA -- Cursor oexfet: 0 (0 kyr)
[18/11/22@16:27:50.546+0100] P-006336 T-002536 1 ORA -- Cursor ofetch: 0 (0 kyr)
[18/11/22@16:27:50.547+0100] P-006336 T-002536 1 ORA -- Cursor ofen : 0 (0 kyr)
[18/11/22@16:27:50.547+0100] P-006336 T-002536 1 ORA -- Cursor obnd* : 0 (0 kyr)
[18/11/22@16:27:50.548+0100] P-006336 T-002536 1 ORA -- Cursor odefin: 0 (0 kyr)
[18/11/22@16:27:50.549+0100] P-006336 T-002536 1 ORA -- Cursor Rows processed 0 (last execution)
[18/11/22@16:27:50.550+0100] P-006336 T-002536 1 ORA -- OCI call OCIHandleFree
[18/11/22@16:27:50.550+0100] P-006336 T-002536 1 ORA -- OCI call 0: 10
[18/11/22@16:27:50.553+0100] P-006336 T-002536 1 ORA -- OCI call OCIHandleFree
[18/11/22@16:27:50.554+0100] P-006336 T-002536 1 ORA -- Logoff from dataserver db as user oech1::3f202e203e2c3e20@glims96. (2690)
```

Lieven

**Comment by lievencardoen** [comment]
And then some more information from the Crash (More at Windows level?):

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	prowin32.exe
  Application Version:	11.6.2.1346
  Application Timestamp:	57963516
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23864
  Fault Module Timestamp:	595fa536
  Exception Code:	c0000005
  Exception Offset:	0000c54f
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	2067
  Additional Information 1:	87ae
  Additional Information 2:	87ae0a4010b75f24897c7025165a9483
  Additional Information 3:	8b50
  Additional Information 4:	8b5030dd54112f50cdcf221acbc3d06f

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

Lieven

**Comment by gquerret** [comment]
The _progres process just crashes, and this is then trapped by the Java part. Does the crash always happen with the same file ? If so, you may need to send the file to Progress, as that's a compiler crash, and not specific to PCT.

**Comment by gquerret** [comment]
Did you get any additional information ? Or can I close the issue ?

**Comment by lievencardoen** [comment]
Hi Gilles, the Progress ABL Compiler seems to crash on the COMPILE statement.

However, if I isolate the problem and try doing the same in Eclipse for instance, then it doesn't crash. So while I think it is a Progress bug, it must have something to do with the way PCT works (I think).

You can close it. We'll try upgrading to latest PCT version. And then we'll see from there.

**Comment by lievencardoen** [comment]
Hi Gilles,

Just wanted to add a log for other developers.

In the meantime we've upgraded to latest version of PCT.

Today I had the same problem again where compiling a certain class made the whole thing crash. I didn't even get a protrace file. This was the last output of Jenkins:

```
10:54:33       [exec]      [echo] ********************************************************************************
10:54:33       [exec] [pct:compile] Result: -1073741819
10:54:33       [exec]      [echo] Error compiling one or more classes
```

Looks like the problem was the path of the file being too long. The class name was already very long, but because of how projects are set up in Jenkins, the absolute path of the filename can get very long.

Shortening the class name made the problem go away. But shortening Jenkins Project name als fixed the issue.

The real problem to me however is that Progress isn't able to just provide everyone with a clear message.

Lieven

**Comment by gquerret** [comment]
Thank you !

**Comment by movedoa** [comment]
@lievencardoen Did you report that to the techsupport? 
This is a horrible bug. But great to have the info since this seems like something that just pops up one day.

**Comment by lievencardoen** [comment]
Well... I'm kind of tired of reporting things to techsupport. They always are very friendly, but most of the time the suggestion is to create an enhancement Idea on the Community platform.
