### ISSUE TITLE
ABLDuck terminates with String index out of range: -1 on certain sources

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#357]
### ABLDuck fails on certain sources and stops without reporting the source
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### Your environment
* Windows 2016
* OpenEdge version 11.7.4
* Ant 1.9.9
* PCT 2.11

### Actual behaviour
```
ant
Buildfile: X:\cce\ablduck_fail\build.xml

ClassDocumentation_Duck:
  [ABLDuck] Generating ABLDuck documentation (11.5+ method)

BUILD FAILED
X:\cce\ablduck_fail\build.xml:15: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at za.co.mip.ablduck.Comment.parseJavadocComment(Comment.java:215)
        at za.co.mip.ablduck.Comment.parseComment(Comment.java:69)
        at za.co.mip.ablduck.ABLDuckClassVisitor.parseComment(ABLDuckClassVisitor.java:388)
        at za.co.mip.ablduck.ABLDuckClassVisitor.readMethod(ABLDuckClassVisitor.java:238)
        at za.co.mip.ablduck.ABLDuckClassVisitor.getCompilationUnit(ABLDuckClassVisitor.java:143)
        at za.co.mip.ablduck.ABLDuck.execute(ABLDuck.java:224)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 0 seconds
```

### Expected behaviour
In order of preference

- Generating documentation succeeds for all file

- Generating documentation reports the file with an issue, skips it and continues with the rest

- Generating documentation reports the file with an issue

### Steps to reproduce
The attached zip contains one file that fails, I can provide more files that fail if needed.
[ablduck_fail.zip](https://github.com/Riverside-Software/pct/files/3080524/ablduck_fail.zip)

**Comment by cverbiest** [comment]
I found this is a regression between builds 210 and 211.
Using the same java / ant / progress / openedge version only changing PCT.jar from build 210 to 211

### with PCT.jar build 210
```
ablduck_fail>ant -lib . -v
Apache Ant(TM) version 1.9.9 compiled on February 2 2017
Trying the default build file: build.xml
Buildfile: X:\cce\ablduck_fail\build.xml
Detected Java version: 1.8 in: C:\apps\java\default\jre
Detected OS: Windows Server 2016
parsing buildfile X:\cce\ablduck_fail\build.xml with URI = file:/X:/cce/ablduck_fail/build.xml
Project base dir set to: X:\cce\ablduck_fail
parsing buildfile jar:file:/C:/apps/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/apps/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
parsing buildfile jar:file:/C:/apps/ant/lib/ant-contrib-1.0b3.jar!/net/sf/antcontrib/antlib.xml with URI = jar:file:/C:/apps/ant/lib/ant-contrib-1.0b3.jar!/net/sf/antcontrib/antlib.xml from a zip file
Build sequence for target(s) `ClassDocumentation_Duck' is [ClassDocumentation_Duck]
Complete build sequence is [ClassDocumentation_Duck, ]

ClassDocumentation_Duck:
[PCTVersion] PCT Version : pct-210-master-86e958f5f04cf2832a2fdc0bb1c471312e0e0f12
    [mkdir] Skipping X:\cce\ablduck_fail\duckdocs because it already exists.
  [ABLDuck] OpenEdge version found : OpenEdge Release 11.7.4 as of Wed Oct 10 19:02:14 EDT 2018
  [ABLDuck] Using object : com.phenix.pct.ProgressV117
  [ABLDuck] Generating ABLDuck documentation (11.5+ method)
  [ABLDuck] Generating AST for X:\cce\ablduck_fail\preprocessed\be\cce\SmartTools\Cache\DataCacheManager.cls
  [ABLDuck] Executing AST ClassVisitor X:\cce\ablduck_fail\preprocessed\be\cce\SmartTools\Cache\DataCacheManager.cls

BUILD SUCCESSFUL
Total time: 0 seconds
```

### with PCT.jar build 211
```


ablduck_fail>ant -lib . -v
Apache Ant(TM) version 1.9.9 compiled on February 2 2017
Trying the default build file: build.xml
Buildfile: X:\cce\ablduck_fail\build.xml
Detected Java version: 1.8 in: C:\apps\java\default\jre
Detected OS: Windows Server 2016
parsing buildfile X:\cce\ablduck_fail\build.xml with URI = file:/X:/cce/ablduck_fail/build.xml
Project base dir set to: X:\cce\ablduck_fail
parsing buildfile jar:file:/C:/apps/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/apps/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
parsing buildfile jar:file:/C:/apps/ant/lib/ant-contrib-1.0b3.jar!/net/sf/antcontrib/antlib.xml with URI = jar:file:/C:/apps/ant/lib/ant-contrib-1.0b3.jar!/net/sf/antcontrib/antlib.xml from a zip file
Build sequence for target(s) `ClassDocumentation_Duck' is [ClassDocumentation_Duck]
Complete build sequence is [ClassDocumentation_Duck, ]

ClassDocumentation_Duck:
[PCTVersion] PCT Version : pct-211-master-7badf2f956c915c0b835eea56c98fad57f2cc7ac
    [mkdir] Skipping X:\cce\ablduck_fail\duckdocs because it already exists.
  [ABLDuck] OpenEdge version found : OpenEdge Release 11.7.4 as of Wed Oct 10 19:02:14 EDT 2018
  [ABLDuck] Using object : com.phenix.pct.ProgressV117
  [ABLDuck] Generating ABLDuck documentation (11.5+ method)
  [ABLDuck] Generating AST for X:\cce\ablduck_fail\preprocessed\be\cce\SmartTools\Cache\DataCacheManager.cls
  [ABLDuck] Executing AST ClassVisitor X:\cce\ablduck_fail\preprocessed\be\cce\SmartTools\Cache\DataCacheManager.cls

BUILD FAILED
X:\cce\ablduck_fail\build.xml:16: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at za.co.mip.ablduck.Comment.parseJavadocComment(Comment.java:215)
        at za.co.mip.ablduck.Comment.parseComment(Comment.java:69)
        at za.co.mip.ablduck.ABLDuckClassVisitor.parseComment(ABLDuckClassVisitor.java:388)
        at za.co.mip.ablduck.ABLDuckClassVisitor.readMethod(ABLDuckClassVisitor.java:238)
        at za.co.mip.ablduck.ABLDuckClassVisitor.getCompilationUnit(ABLDuckClassVisitor.java:143)
        at za.co.mip.ablduck.ABLDuck.execute(ABLDuck.java:224)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 0 seconds
```

**Comment by gquerret** [comment]
Comes from a regression in `@deprecated` tags ; this version always expect a version number and a comment. Fixed in development, those arguments are now optional.

**Comment by cverbiest** [comment]
Could something be done in the line of 

- Generating documentation reports which file has an issue, skips it and continues with the rest

as well ?

Normally I run this without verbose, you then have no idea which file caused it and re-run with verbose to find that out, remove the file and re-run. If there are mutliple files that can't be processed this is a painstaking process.

**Comment by gquerret** [comment]
Can you try this build: https://ci.rssw.eu/job/pct/job/bugfix%252FPCT-357-ABLDuck/ ?
Let me know if there are still issues there.

**Comment by gquerret** [comment]
@cverbiest Did you try this build ?

**Comment by gquerret** [comment]
@cverbiest Did you try this build ?
