### ISSUE TITLE
Exception in BackgroundWorker when using multiple threads

### ISSUE THREAD

**Issue by droppedcalls** [Riverside-Software/pct#363]
### Subject of the issue
When running multiple threads on some systems, in particular our Red Hat Jenkins build agents, the following exception would occur:

```
[PCTCompile] Exception in thread "Thread-1351" java.lang.NullPointerException
[PCTCompile]     at com.phenix.pct.BackgroundWorker.listen(BackgroundWorker.java:105)
[PCTCompile]     at com.phenix.pct.PCTBgRun$ListenerThread$1.run(PCTBgRun.java:686)
[PCTCompile]     at java.lang.Thread.run(Thread.java:748)
```

### Your environment
* RHEL 2.6.32-754.10.1.el6.x86_64
* OpenEdge version 11.7.3
* Apache Ant(TM) version 1.9.6
* PCT version 211

### Actual behaviour
The build succeeds, but several threads may show the above error, which appears to be benign

### Expected behaviour
No errors should be printed
Looking at line 105 in BackgroundWorker.listen(), it is assumed that the read does not return null.

### Steps to reproduce
We only had this issue happen on the Jenkins build agent with a large number of threads

**Comment by droppedcalls** [comment]
I have written a fix already; I just need to rebase before creating a pull request
