### ISSUE TITLE
RestGen fails with java.lang.NoClassDefFoundError under 11.7.4

### ISSUE THREAD

**Issue by jza0330** [Riverside-Software/pct#371]
### Subject of the issue
It looks like getRestGenClasspath method in PCT.java sets incorrect classpath. Class com.openedge.pdt.server.preferences.PublishFilterStorage which is needed for RestGen is in ablwebapp.jar. 

### Your environment
* Windows 64
* OpenEdge 11.7.4
* Ant 1.9.6
* PCT 212

### Actual behaviour
```
<RestGen dlcHome="${env.DLC}" projectDir="." destFile="${dest}/test.war" type="mobwar" services="bc:cont:lic:sys" />
```
fails with this exception
```
[RestGen] Creating Only Mobile Application WAR file with [bc, cont, lic, sys] at target C:\OpenEdge\WRK\git\lms-backend\LMS_Backend_Rest\target\test.war
  [RestGen] Error invoking method. Please check the options provided
  [RestGen] java.lang.reflect.InvocationTargetException
  [RestGen] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [RestGen] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  [RestGen] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [RestGen] 	at java.lang.reflect.Method.invoke(Method.java:498)
  [RestGen] 	at com.progress.rest.tools.WARGenerator.createOnlyMobileApplicationWarWrapper(WARGenerator.java:116)
  [RestGen] 	at com.progress.rest.tools.WARGenerator.main(WARGenerator.java:425)
  [RestGen] Caused by: java.lang.NoClassDefFoundError: com/openedge/pdt/server/preferences/PublishFilterStorage
  [RestGen] 	at com.progress.openedge.pdt.rest.util.RestUtil.loadPublishFilters(RestUtil.java:1035)
  [RestGen] 	at com.progress.openedge.pdt.rest.util.RESTWARGenerator.filterResources(RESTWARGenerator.java:265)
  [RestGen] 	at com.progress.openedge.pdt.rest.util.RESTWARGenerator.copyRestContentFolderToTemp(RESTWARGenerator.java:256)
  [RestGen] 	at com.progress.openedge.pdt.rest.util.RESTWARGenerator.copyRestContentFolderToTemp(RESTWARGenerator.java:206)
  [RestGen] 	at com.progress.openedge.pdt.oemobile.designer.util.MobileAppWARGenerator.createMobileApplicationWar(MobileAppWARGenerator.java:86)
  [RestGen] 	at com.progress.openedge.pdt.oemobile.designer.util.MobileAppWARGenerator.createOnlyMobileApplicationWar(MobileAppWARGenerator.java:70)
  [RestGen] 	at com.progress.openedge.pdt.oemobile.designer.util.MobileAppWARGenerator.createOnlyMobileApplicationWar(MobileAppWARGenerator.java:63)
  [RestGen] 	... 6 more
  [RestGen] Caused by: java.lang.ClassNotFoundException: com.openedge.pdt.server.preferences.PublishFilterStorage
  [RestGen] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  [RestGen] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  [RestGen] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  [RestGen] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  [RestGen] 	... 13 more
  [RestGen] Java Result: 1
```

**Classpath from verbose logging:**
```
 [RestGen] '-classpath'
  [RestGen] 'c:\Progress\OpenEdge\java\progress.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.openedge.pdt.core_11.7.4.00\oe_common_services.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.openedge.pdt.explorer_11.7.4.00\prgsexplorer.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.openedge.pdt.platform_11.7.4.00\platform.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.openedge.pdt.project_11.7.4.00\oeproject.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.openedge.pdt.oemobile.designer_11.7.4.00\mobdesigner.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.openedge.pdt.oemobile_11.7.4.00\oemobile.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.openedge.pdt.pex_11.7.4.00\pex.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.openedge.pdt.rest_11.7.4.00\lib\jettison-1.2.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.openedge.pdt.rest_11.7.4.00\rest.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.openedge.pdt.restoe_11.7.4.00\lib\1padapters-idl.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.branding.iue_2.6.0\lib\velocity-1.7-dep.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.branding.iue_2.6.0\lib\velocity-1.7.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.adapter.rest.core_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.adapter.rest.expose.core_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.adapter.rest.expose.ui_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.adapter.rest.mapper_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.archiver_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.core_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.runtime_1.6.0\lib\framework\lib\log4j\log4j-1.2.16.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.runtime_1.6.0\lib\rest\expose\1padapters-restExpose.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.caf.ui.mapper_1.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.common.ui.el_2.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.common.ui.mapper.el_2.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.common.ui.mapper_2.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.common.ui_2.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\com.progress.tools.installinfo_2.6.0.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.databinding.observable_1.5.0.v20150422-0725.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.databinding.property_1.5.0.v20150422-0725.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.databinding_1.5.0.v20150422-0725.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.filesystem_1.5.0.v20150725-1910.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.jobs_3.7.0.v20150330-2103.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.resources_3.10.1.v20150725-1910.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.core.runtime_3.11.1.v20150903-1804.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.debug.core_3.10.0.v20150303-1130.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.debug.ui_3.11.101.v20160203-1230.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.common_2.11.0.v20150805-0538.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.common_2.11.1.v20160208-0816.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.databinding_1.3.0.v20150806-0404.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.databinding_1.3.0.v20160208-0841.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.ecore.xmi_2.11.1.v20150805-0538.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.ecore.xmi_2.11.1.v20160208-0816.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.ecore_2.11.1.v20150805-0538.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.emf.ecore_2.11.2.v20160208-0816.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.equinox.common_3.7.0.v20150402-1709.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.equinox.preferences_3.5.300.v20150408-1437.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.jface_3.11.1.v20160128-1644.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.osgi_3.10.102.v20160118-1700.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.swt_3.104.2.v20160212-1350.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.text_3.5.400.v20150505-1044.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.ui.ide_3.11.0.v20150825-2158.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.ui.workbench_3.107.1.v20160120-2131.jar;c:\Progress\OpenEdge\oeide\eclipse\plugins\org.eclipse.wst.server.core_1.8.0.v201601132216.jar'
```
### Expected behaviour
Add ablwebapp.jar to getRestGenClasspath method in PCT.java. Maybe also other jars. I did not tested it.

### Steps to reproduce

1. In OE Development studio create sample server project for the web transport
2. Use the same restgen task as above

**Comment by gquerret** [comment]
Sorry for delay, won't be able to have a look before the beginning of August...

**Comment by gquerret** [comment]
Reproduced. Could you just try to generate the output with %DLC%\bin\restgen.bat ? I've quickly tried to do that, but got another error (also with missing class), so I may have to contact Progress to get the right classpath.

**Comment by jza0330** [comment]
same problem with restgen at my side when using genMobAppWar. When using genRESTWar then no problems occured.
I also think they changed the classpath between service pack versions. that's why pct is having problems now. Anyway I am using as workaround(documented in OpenEdge doc)

`<ABLWebAppPackage srcdir="." dlc="${env.DLC}" verbose="true" isIncremental="false" webAppName="lms" destdir="${dest.dir}" />`

```
<taskdef resource="com/progress/openedge/pdt/ant/ablwebapp/ablwebapps.properties">
			<classpath>
				<pathelement location="${dlc.java.dir}/ant-ablwebapp.jar" />

				<!-- ABLWebApp Dependencies -->
				<pathelement location="${dlc.java.dir}/ant-libs/ablwebapp.jar" />
				<pathelement location="${dlc.java.dir}/ant-libs/ablwebapp-dependencies.jar" />

				<!-- CodeModel Dependencies -->
				<pathelement location="${dlc.java.dir}/ant-libs/codemodel-dependencies.jar" />

				<!-- AST and its Dependencies -->
				<pathelement location="${dlc.java.dir}/ant-libs/ast.jar" />
				<pathelement location="${dlc.java.dir}/ant-libs/ast-dependencies.jar" />

				<!-- Additional deps -->
				<pathelement location="${dlc.java.dir}/ant-libs/velocity-1.7.jar" />
				<pathelement location="${dlc.java.dir}/ant-libs/velocity-1.7-dep.jar" />
				<pathelement location="${dlc.java.dir}/ant-libs/1padapters-restExpose.jar" />
				<pathelement location="${dlc.java.dir}/1padapters-idl.jar" />
				<pathelement location="${dlc.java.dir}/ext/jettison-1.2.jar" />
			</classpath>
</taskdef>
```

**Comment by gquerret** [comment]
Classpath changed in 11.7, but also in 12.x.
Probably a good time to switch to the standard Progress tasks...
