### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by hutcj** [Riverside-Software/pct#386]
### Error when trying to use ANT PCT:
Following quick start guide here: https://github.com/Riverside-Software/pct/wiki/QuickStart
```
build.xml:4: java.lang.UnsupportedClassVersionError: (com/phenix/pct/DlcHome) bad major version at offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:267)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:602)
        at java.net.URLClassLoader.access$400(URLClassLoader.java:126)
        at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1057)
        at java.security.AccessController.doPrivileged(AccessController.java:414)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:494)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:651)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:617)
        at org.apache.tools.ant.AntClassLoader.findBaseClass(AntClassLoader.java:1405)
        at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1086)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:617)
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:237)
        at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:579)
        at org.apache.tools.ant.taskdefs.Definer.loadProperties(Definer.java:408)
        at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:264)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:79)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:619)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:180)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
        at org.apache.tools.ant.Main.runBuild(Main.java:832)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
```

### Your environment
* AIX 7.1
* OpenEdge 11.7.5
* Ant 1.9.8 (using $DLC/bin/proant)
* PCT 213

`$ java -version`
```
java version "1.5.0"
Java(TM) 2 Runtime Environment, Standard Edition (build pap64devifx-20151009 (SR16 FP14 ))
IBM J9 VM (build 2.3, J2RE 1.5.0 IBM J9 2.3 AIX ppc64-64 j9vmap6423ifx-20150401 (JIT enabled)
J9VM - 20150323_240985_BHdSMr
JIT  - 20130920_46470ifx2_r8
GC   - 20141118_AA)
JCL  - 20151009
```

`$ javac -version`
```
javac 1.5.0
...
```

### Actual behaviour
Any attempt to run a build.xml (`$ proant` in the directory where the build.xml file is) results in the error above.

### Expected behaviour
Perform the build. I have been able to run ANT PCT builds on Windows, but have not been able to run on AIX. Is AIX supported, or do I have a Java problem?

### Steps to reproduce
It seems like this could be a Java version issue - is there a specific Java version required by PCT? The ANT documentation says Java 1.5 should work with Ant 1.9.

Thank you!
-- Jonathan Hutchens

**Comment by gquerret** [comment]
It's a Java version problem, PCT requires 1.7 since version 208 (when 11.7 was introduced). Make sure the JAVA_HOME environment variable points to $DLC/jdk before running proant.

**Comment by hutcj** [comment]
Thank you, setting JAVA_HOME to $DLC/jdk fixed the problem.
