### ISSUE TITLE
PCT fails to load extras11.5properties :  A class needed by class eu.rssw.pct.oedoc.OpenEdgeDocumentation115 cannot be found: javax.xml.bind.JAXBException  using the classloader AntClassLoader[]

### ISSUE THREAD

**Issue by PeterJudgeZA** [Riverside-Software/pct#404]
### Subject of the issue
Trying to run tasks from Jenkins, and see the error when trying to run a task
"A class needed by class eu.rssw.pct.oedoc.OpenEdgeDocumentation115 cannot be found: javax.xml.bind.JAXBException  using the classloader AntClassLoader[]"

### Your environment
* Windows 10-64
* OpenEdge 12.2.0 
* Ant version: 1.10.6
* PCT version: 212 

The build step in Jenkins has the following target:
build-corelib  -lib $DLC/java/ant-libs/ast.jar  -lib $DLC/java/ant-libs/ast-dependencies.jar -lib $DLC/pct/PCT.jar -lib $DLC/ant/lib/ant-contrib-0.6.jar -v 

### Expected behaviour
Life should be good and I should be able to run the tasks

### Steps to reproduce
build.xml: 14: <taskdef resource="extras115.properties" />

The Build Console from Jenkins is 
```
Started by user PJ
Running as SYSTEM
Building in workspace C:\devarea\views\pjudge_OE123
[117] $ cmd.exe /C "c:\devarea\dlc\oe122\ant\bin\ant.bat -file build.xml -Dbuild.root=C:/devarea/views/pjudge_OE123/vobs_possenet build-corelib -lib c:\devarea\dlc\oe122/java/ant-libs/ast.jar -lib c:\devarea\dlc\oe122/java/ant-libs/ast-dependencies.jar -lib c:\devarea\dlc\oe122/pct/PCT.jar -lib c:\devarea\dlc\oe122/ant/lib/ant-contrib-0.6.jar -v && exit %%ERRORLEVEL%%"
Apache Ant(TM) version 1.10.6 compiled on May 2 2019
Buildfile: C:\devarea\build\117\build.xml
Detected Java version: 11 in: C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-openj9
Detected OS: Windows 10
parsing buildfile C:\devarea\build\117\build.xml with URI = file:/C:/devarea/build/117/build.xml
Project base dir set to: C:\devarea\build\117
parsing buildfile jar:file:/C:/devarea/dlc/oe122/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/devarea/dlc/oe122/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Property "env.BUILD_ROOT" has not been set
Override ignored for property "build.root"

BUILD FAILED
C:\devarea\build\117\build.xml:14: taskdef A class needed by class eu.rssw.pct.oedoc.OpenEdgeDocumentation115 cannot be found: javax.xml.bind.JAXBException
 using the classloader AntClassLoader[]
	at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:603)
	at org.apache.tools.ant.taskdefs.Definer.loadProperties(Definer.java:401)
	at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:263)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:184)
	at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
	at org.apache.tools.ant.Main.runBuild(Main.java:805)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.NoClassDefFoundError: javax.xml.bind.JAXBException
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:410)
	at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:569)
	... 16 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:605)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1169)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1084)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1067)
	... 19 more

Total time: 0 seconds
Build step 'Invoke Ant' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did leafNodes run? 
For example, C:\devarea\views\pjudge_OE123\vobs_possenet_qa\tests\build\corelib\results.xml is 19 min old

Finished: FAILURE
```

**Comment by stefandrissen** [comment]
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by PeterJudgeZA** [comment]
@stefandrissen Thanks (again). This means PCT doesn't support ClassDoc for java 11. (I was trying to use the in-the-OE-box PCT and java, but I'll have to try something else).

**Comment by PeterJudgeZA** [comment]
Jenkins lets me specify the OpenJDK-8 I have installed, but other issues result

```
Detected Java version: 1.8 in: C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-openj9\jre
Detected OS: Windows 10
parsing buildfile C:\devarea\build\117\build.xml with URI = file:/C:/devarea/build/117/build.xml
Project base dir set to: C:\devarea\build\117
parsing buildfile jar:file:/C:/devarea/dlc/oe122/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/devarea/dlc/oe122/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Property "env.BUILD_ROOT" has not been set
Override ignored for property "build.root"

BUILD FAILED
C:\devarea\build\117\build.xml:14: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/openedge/core/runtime/IPropath, offset=6
```

**Comment by PeterJudgeZA** [comment]
![404](https://user-images.githubusercontent.com/8291561/74985759-237aaa80-5406-11ea-9051-c4b851df2b70.png)

It seems appropriate that issue 404 is about something not found.

**Comment by stefandrissen** [comment]
I think the bad major version is a result of (some alpha) PSC IPropath being compiled with Java 11 and you are now trying to run it with (open) Java 8?

Ultimately I would guess that PCT needs to work with Java 11, this is @gquerret  area of expertise.

**Comment by gquerret** [comment]
OpenEdge 12.2 is the first version where class files are compiled with JDK 11, so OpenJDK 8 is not going  to work whatever you do.
The JAXBException message can be solved by adding `-lib jaxb-api.jar -lib jaxb-core.jar -lib jaxb-impl.jar -lib activation.jar` in your command line. Those JAR files can be found in the PCT repository (`lib` directory).
Short explanation: JAXB (a library for XML processing) has been removed from the standard Java libraries as of Java 9, so any program having a dependency on it has to include it in the classpath. PCT itself doesn't need JAXB, so it's not included in PCT, but the Progress parser requires it.

**Comment by gquerret** [comment]
And I can confirm ClassDocumentation is already working: https://ci.rssw.eu/job/PCT/job/feature%252FAnt110Corretto11/

This PCT branch is using Ant 1.10 and Amazon Corretto 11 (an OpenJDK implementation) for all unit tests.

**Comment by PeterJudgeZA** [comment]
Thanks @gquerret . I'll close this ticket.

**Comment by PeterJudgeZA** [comment]
In case anyone comes across this: in OE12.2 all of those jars are in $DLC/java/ext/ .

My Ant targets line is now
 doc-corelib   -lib $DLC/java/ant-libs/ast.jar  -lib $DLC/java/ant-libs/ast-dependencies.jar -lib $DLC/pct/PCT.jar -lib $DLC/ant/lib/ant-contrib-0.6.jar  -lib $DLC/java/ext/jaxb-api-2.3.1.jar -lib $DLC/java/ext/jaxb-core-2.3.0.1.jar -lib $DLC/java/ext/jaxb-impl-2.3.2.jar -lib $DLC/java/ext/activation.jar

**Comment by gquerret** [comment]
😱😱 `-lib $DLC/ant/lib/ant-contrib-0.6.jar` 😱😱

Not only for ant-contrib, but also for version 0.6 which was released in 2003...

**Comment by PeterJudgeZA** [comment]
That makes it stable, no?

;)
