### ISSUE TITLE
PCTDumpIncremental return code 1

### ISSUE THREAD

**Issue by hutcj** [Riverside-Software/pct#409]
### PCTDumpIncremental return code 1
This task is returning error code 1 when attempting to run. At first I was running through groovy, but when that didn't work moved to straight Ant - this did not work either.

### Your environment
* AIX 7
* OpenEdge 11.7.5
* Ant 1.9.8
* PCT 213

### Actual behaviour
(verbose output enabled)
```
build:
[PCTDumpIncremental] OpenEdge version found : OpenEdge Release 11.7.5 as of Fri Jun  7 09:00:44 EDT 2019
[PCTDumpIncremental] Using object : com.phenix.pct.ProgressV117
[PCTDumpIncremental] Creating incremental DF from source to target
[PCTDumpIncremental] Current OS is AIX
[PCTDumpIncremental] Setting environment variable: DLC=/progress/oe117
[PCTDumpIncremental] Executing '/progress/oe117/bin/_progres' with arguments:
[PCTDumpIncremental] '-b'
[PCTDumpIncremental] '-q'
[PCTDumpIncremental] '-cpstream'
[PCTDumpIncremental] 'ISO8859-1'
[PCTDumpIncremental] '-p'
[PCTDumpIncremental] '/tmp/pctinit52358364.p'
[PCTDumpIncremental]
[PCTDumpIncremental] The ' characters around the executable and arguments are
[PCTDumpIncremental] not part of the command.
[PCTDumpIncremental] Trying to connect to : -db ./db/favadm.db -ld source -1 -RO
[PCTDumpIncremental] Creating alias dictdb for database 1
[PCTDumpIncremental] Trying to connect to : -db ./temp/temp_favadm.db -ld target -1 -RO
[PCTDumpIncremental] Creating alias dictdb2 for database 2
[PCTDumpIncremental] PROPATH : /tmp/pct105031758.pl,/f/rcode,/coins,/coinsprog/sa,/progress/oe117/tty/netlib/OpenEdge.Net.pl,/f/pdfinc,./,/wp/hutcj,/progress/oe117/tty,/progress/oe117/tty/OpenEdge.Core.pl,/progress/oe117/tty/ablunit.pl,/progress/oe117/tty/adecomm.pl,/progress/oe117/tty/adecomp.pl,/progress/oe117/tty/adeedit.pl,/progress/oe117/tty/adeshar.pl,/progress/oe117/tty/dataadmin.pl,/progress/oe117/tty/prodict.pl,/progress/oe117,/progress/oe117/bin
[PCTDumpIncremental] RUN pct/v11/silentIncDump114.p
[PCTDumpIncremental] Return value : 1
```
No other error messages/reasons are given for the failure or to describe exactly what went wrong. Incremental df file is not generated.

### Expected behaviour
Incremental df file to be generated, success message displayed or similar.

### Steps to reproduce
Sample build file:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<project name="test-proj" default="build" basedir=".">

  <property environment="env" />
  <property name="DLC" value="${env.DLC}" />
  <property name="TARGET" value="${basedir}/target" />
  <property name="BUILD" value="${TARGET}/build" />
  <property name="GROOVY_LIB" value="/opt/groovy-2.5.9/lib" />

  <!-- -pct-def: PCT definitions -->
  <target name="-pct-def">
    <!-- PCT Libraries -->
    <taskdef resource="PCT.properties" />
    <typedef resource="types.properties" />
    <!-- Next line only for tasks using OpenEdge parser, see ClassDocumentation task -->
    <!--<typedef resource="extras.properties" />-->
    <PCTVersion />
  </target>

  <!-- -groovy-def: Groovy definitions -->
  <target name="-groovy-def">
    <echo message="Groovy lib: ${GROOVY_LIB}" />
    <taskdef name="groovy" classname="org.codehaus.groovy.ant.Groovy">
      <classpath>
        <fileset file="${GROOVY_LIB}/groovy-ant-2.5.9.jar"/>
        <fileset file="${GROOVY_LIB}/groovy-2.5.9.jar"/>
      </classpath>
    </taskdef>
  </target>

  <target name="build" depends="-pct-def,-groovy-def">
    <PCTDumpIncremental dlcHome="${DLC}" cpstream="ISO8859-1" destFile="./databases/db4/deltas/0005/delta.df" renameFile="test.rf">
      <SourceDb dbName="./db/favadm.db" readOnly="true" singleUser="true" logicalName="source" />
      <TargetDb dbName="./temp/temp_favadm.db" readOnly="true" singleUser="true" logicalName="target" />
    </PCTDumpIncremental>
  </target>

</project>
```

**Comment by gquerret** [comment]
Can you try without the renameFile attribute ? Just to see where the problem could lie...

**Comment by hutcj** [comment]
Ok, tried again without specifying a rename file - no difference. I double checked by doing a manual incremental df with the data dictionary connecting to the same databases - no issues with that.

**Comment by stefandrissen** [comment]
There are multiple differences between _dmpincr114.p and 11.7 _dmpincr.p. 

An extra error ``63`` has been added ``database. A partitioned table cannot be changed into non partitioned table.`` and the check on input parameter index-mode has changed from ``NE "0"`` to ``NE "active"`` - this parameter is passed by PCTDumpIncremental.java.

Another problem /may/ be that the shared variable definitions in prodict/dictvar.i have changed, these are now extent 480 (was: 64):
````
DEFINE {1} SHARED VARIABLE cache_db_s       AS CHARACTER EXTENT 480  NO-UNDO.
DEFINE {1} SHARED VARIABLE cache_db_l       AS CHARACTER EXTENT 480  NO-UNDO.
DEFINE {1} SHARED VARIABLE cache_db_p       AS CHARACTER EXTENT 480  NO-UNDO.
DEFINE {1} SHARED VARIABLE cache_db_t       AS CHARACTER EXTENT 480  NO-UNDO.
DEFINE {1} SHARED VARIABLE cache_db_e       AS CHARACTER EXTENT 480  NO-UNDO.
````

**Comment by gquerret** [comment]
Unit tests are already executed on 11.7.5, so that's supposed to work correctly. Can you also include `<PCTVersion /> ` during the execution of your script, in order to confirm the version number of PCT ?
Could you also try [this version of PCT](https://ci.rssw.eu/job/PCT/job/feature%252FLogMsg/lastSuccessfulBuild/artifact/dist/PCT.jar) ? You should have a stack trace with your error.

**Comment by hutcj** [comment]
Yes, I did see a stack trace but had only posted part of the build output. Here is the full output:
```
Apache Ant(TM) version 1.9.8 compiled on December 25 2016
Trying the default build file: build.xml
Buildfile: /wp/hutcj/schema/build.xml
Detected Java version: 1.8 in: /progress/oe117/jdk/jre
Detected OS: AIX
parsing buildfile /wp/hutcj/schema/build.xml with URI = file:/wp/hutcj/schema/build.xml
Project base dir set to: /wp/hutcj/schema
parsing buildfile jar:file:/progress/oe117/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/progress/oe117/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Build sequence for target(s) `build' is [-pct-def, -groovy-def, build]
Complete build sequence is [-pct-def, -groovy-def, build, ]

-pct-def:
[PCTVersion] PCT Version : pct-213-master-371bf8991b070175bdc34298b8c6ccb5b3e5a4a1

-groovy-def:
     [echo] Groovy lib: /opt/groovy-2.5.9/lib

build:
[PCTDumpIncremental] OpenEdge version found : OpenEdge Release 11.7.5 as of Fri Jun  7 09:00:44 EDT 2019
[PCTDumpIncremental] Using object : com.phenix.pct.ProgressV117
[PCTDumpIncremental] Creating incremental DF from source to target
[PCTDumpIncremental] Current OS is AIX
[PCTDumpIncremental] Setting environment variable: DLC=/progress/oe117
[PCTDumpIncremental] Executing '/progress/oe117/bin/_progres' with arguments:
[PCTDumpIncremental] '-b'
[PCTDumpIncremental] '-q'
[PCTDumpIncremental] '-cpstream'
[PCTDumpIncremental] 'ISO8859-1'
[PCTDumpIncremental] '-p'
[PCTDumpIncremental] '/tmp/pctinit22253533.p'
[PCTDumpIncremental]
[PCTDumpIncremental] The ' characters around the executable and arguments are
[PCTDumpIncremental] not part of the command.
[PCTDumpIncremental] Trying to connect to : -db ./db/favadm.db -ld source -1 -RO
[PCTDumpIncremental] Creating alias dictdb for database 1
[PCTDumpIncremental] Trying to connect to : -db ./temp/temp_favadm.db -ld target -1 -RO
[PCTDumpIncremental] Creating alias dictdb2 for database 2
[PCTDumpIncremental] PROPATH : /tmp/pct204165946.pl,/f/rcode,/coins,/coinsprog/sa,/progress/oe117/tty/netlib/OpenEdge.Net.pl,/f/pdfinc,./,/wp/hutcj,/progress/oe117/tty,/progress/oe117/tty/OpenEdge.Core.pl,/progress/oe117/tty/ablunit.pl,/progress/oe117/tty/adecomm.pl,/progress/oe117/tty/adecomp.pl,/progress/oe117/tty/adeedit.pl,/progress/oe117/tty/adeshar.pl,/progress/oe117/tty/dataadmin.pl,/progress/oe117/tty/prodict.pl,/progress/oe117,/progress/oe117/bin
[PCTDumpIncremental] RUN pct/v11/silentIncDump114.p
[PCTDumpIncremental] Return value : 1

BUILD FAILED
/wp/hutcj/schema/build.xml:32: Return code : 1
        at com.phenix.pct.PCTRun.execute(PCTRun.java:458)
        at com.phenix.pct.PCTDumpIncremental.execute(PCTDumpIncremental.java:200)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 1 second
```

**Comment by hutcj** [comment]
Here is the result from the newer version of PCT:
```
Apache Ant(TM) version 1.9.8 compiled on December 25 2016
Trying the default build file: build.xml
Buildfile: /wp/hutcj/schema/build.xml
Detected Java version: 1.8 in: /progress/oe117/jdk/jre
Detected OS: AIX
parsing buildfile /wp/hutcj/schema/build.xml with URI = file:/wp/hutcj/schema/build.xml
Project base dir set to: /wp/hutcj/schema
parsing buildfile jar:file:/progress/oe117/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/progress/oe117/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Build sequence for target(s) `build' is [-pct-def, -groovy-def, build]
Complete build sequence is [-pct-def, -groovy-def, build, ]

-pct-def:
[PCTVersion] PCT Version : pct-216.pre-feature/LogMsg-21ae71740bb7405d35d28956d285a5811a20fa9d

-groovy-def:
     [echo] Groovy lib: /opt/groovy-2.5.9/lib

build:
[PCTDumpIncremental] OpenEdge version found : OpenEdge Release 11.7.5 as of Fri Jun  7 09:00:44 EDT 2019
[PCTDumpIncremental] Using object : com.phenix.pct.ProgressV117
[PCTDumpIncremental] Creating incremental DF from source to target
[PCTDumpIncremental] Current OS is AIX
[PCTDumpIncremental] Setting environment variable: DLC=/progress/oe117
[PCTDumpIncremental] Executing '/progress/oe117/bin/_progres' with arguments:
[PCTDumpIncremental] '-b'
[PCTDumpIncremental] '-q'
[PCTDumpIncremental] '-cpstream'
[PCTDumpIncremental] 'ISO8859-1'
[PCTDumpIncremental] '-p'
[PCTDumpIncremental] '/tmp/pctinit240454439.p'
[PCTDumpIncremental]
[PCTDumpIncremental] The ' characters around the executable and arguments are
[PCTDumpIncremental] not part of the command.
[PCTDumpIncremental] Trying to connect to : -db ./db/favadm.db -ld source -1 -RO
[PCTDumpIncremental] Creating alias dictdb for database 1
[PCTDumpIncremental] Trying to connect to : -db ./temp/temp_favadm.db -ld target -1 -RO
[PCTDumpIncremental] Creating alias dictdb2 for database 2
[PCTDumpIncremental] PROPATH : /tmp/pct222472329.pl,/f/rcode,/coins,/coinsprog/sa,/progress/oe117/tty/netlib/OpenEdge.Net.pl,/f/pdfinc,./,/wp/hutcj,/progress/oe117/tty,/progress/oe117/tty/OpenEdge.Core.pl,/progress/oe117/tty/ablunit.pl,/progress/oe117/tty/adecomm.pl,/progress/oe117/tty/adecomp.pl,/progress/oe117/tty/adeedit.pl,/progress/oe117/tty/adeshar.pl,/progress/oe117/tty/dataadmin.pl,/progress/oe117/tty/prodict.pl,/progress/oe117,/progress/oe117/bin
[PCTDumpIncremental] RUN pct/v11/silentIncDump114.p
[PCTDumpIncremental] Return value : 1

BUILD FAILED
/wp/hutcj/schema/build.xml:32: Return code : 1
        at com.phenix.pct.PCTRun.execute(PCTRun.java:458)
        at com.phenix.pct.PCTDumpIncremental.execute(PCTDumpIncremental.java:200)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 1 second
```

**Comment by gquerret** [comment]
My small change didn't bring the expected output :-(
Could you try adding attribute `debugLevel="2"` to the `<PCTDumpIncremental>` task, and also add:
```
<Parameter name="-clientlog" value="log.txt" />
<Parameter name="-logentrytypes" value="4GLTrace:4" />
```
You should then have two files `incrdump.e` and `log.txt` with hopefully some interesting content.

**Comment by hutcj** [comment]
Ok, so I tried this with PCT-213 and PCT-216 pre-release. The client log file is not being generated for some reason. I also tried using an absolute filesystem path for the file, but it still wasn't created. I also tried creating the file first, but no difference there, either.

Here is the output I got from ```incrdump.e```:

```
Using default value of "ISO8859-1" for code page.
DUMP_INC_DFFILE     = /wp/hutcj/schema/databases/db4/deltas/0005/delta.df
DUMP_INC_CODEPAGE   = ISO8859-1
DUMP_INC_INDEXMODE  = 0
DUMP_INC_RENAMEFILE =
DUMP_INC_DEBUG      = 2
SHDBNAME1           =
MSSDBNAME1          =
ORADBNAME1          =
SHDBNAME2           =
MSSDBNAME2          =
ORADBNAME2          =
```

This is what I used for the dump task:
```
    <PCTDumpIncremental dlcHome="${DLC}" cpstream="ISO8859-1" destFile="./databases/db4/deltas/0005/delta.df" debugLevel="2">
      <Parameter name="-clientlog" value="/wp/hutcj/schema/log.txt" />
      <Parameter name="-logentrytypes" value="4GLTrace:4" />
      <SourceDb dbName="./db/favadm.db" readOnly="true" singleUser="true" logicalName="source" />
      <TargetDb dbName="./temp/temp_favadm.db" readOnly="true" singleUser="true" logicalName="target" />
    </PCTDumpIncremental>
```

**Comment by gquerret** [comment]
Typed too fast, I meant:
```
<Option name="-clientlog" value="log.txt" />
<Option name="-logentrytypes" value="4GLTrace:4" />
```

**Comment by hutcj** [comment]
Ok, here we go:
```
[20/03/19@07:22:15.267-0500] P-9896160 T-000001 1 4GL -- Logging level set to = 2
[20/03/19@07:22:15.267-0500] P-9896160 T-000001 1 4GL -- Log entry types activated: 4GLTrace:4
[20/03/19@07:22:15.332-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run pct/v11/silentIncDump114.p [Main Block - /tmp/pctinit12631002.p @ 57]
[20/03/19@07:22:15.332-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run pct/v11/dump_inc114.p PERSIST [Main Block - pct/v11/silentIncDump114.p @ 22]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from Main Block [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Func getParameter in /tmp/pctinit12631002.p "DFFileName" [Main Block - pct/v11/silentIncDump114.p @ 24]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getParameter "/wp/hutcj/schema/databases/db4/deltas/0005/delta.df" [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setFileName in pct/v11/dump_inc114.p "/wp/hutcj/schema/databases/db4/deltas/0005/delta.df" [Main Block - pct/v11/silentIncDump114.p @ 24]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setFileName [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Func getParameter in /tmp/pctinit12631002.p "CodePage" [Main Block - pct/v11/silentIncDump114.p @ 25]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getParameter "" [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setCodePage in pct/v11/dump_inc114.p "" [Main Block - pct/v11/silentIncDump114.p @ 25]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setCodePage [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Func getParameter in /tmp/pctinit12631002.p "IndexMode" [Main Block - pct/v11/silentIncDump114.p @ 26]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getParameter "0" [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setIndexMode in pct/v11/dump_inc114.p "0" [Main Block - pct/v11/silentIncDump114.p @ 26]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setIndexMode [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Func getParameter in /tmp/pctinit12631002.p "RenameFile" [Main Block - pct/v11/silentIncDump114.p @ 27]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getParameter "" [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setRenameFilename in pct/v11/dump_inc114.p "" [Main Block - pct/v11/silentIncDump114.p @ 27]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setRenameFilename [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Func getParameter in /tmp/pctinit12631002.p "DebugMode" [Main Block - pct/v11/silentIncDump114.p @ 28]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getParameter "2" [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setDebugMode in pct/v11/dump_inc114.p "2" [Main Block - pct/v11/silentIncDump114.p @ 28]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setDebugMode [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Func getParameter in /tmp/pctinit12631002.p "removeEmptyDFfile" [Main Block - pct/v11/silentIncDump114.p @ 29]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getParameter "false" [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setRemoveEmptyDFfile in pct/v11/dump_inc114.p "no" [Main Block - pct/v11/silentIncDump114.p @ 29]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setRemoveEmptyDFfile [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run setSilent in pct/v11/dump_inc114.p "yes" [Main Block - pct/v11/silentIncDump114.p @ 30]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from setSilent [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.333-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run doDumpIncr in pct/v11/dump_inc114.p [Main Block - pct/v11/silentIncDump114.p @ 31]
[20/03/19@07:22:15.334-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run pct/v11/_dmpincr114.p [doDumpIncr - pct/v11/dump_inc114.p @ 965]
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getEpolicyObj [prodict.sec._sec-pol-util] ERROR
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from _sec-pol-util [prodict.sec._sec-pol-util] ERROR
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from getEpolicyObj [prodict.sec._sec-pol-util] ERROR
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from _sec-pol-util [prodict.sec._sec-pol-util] ERROR
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from doDumpIncr [pct/v11/dump_inc114.p]
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from Main Block [pct/v11/silentIncDump114.p]
[20/03/19@07:22:15.364-0500] P-9896160 T-000001 2 4GL 4GLTRACE       Run returnValue "1" [Main Block - /tmp/pctinit12631002.p @ 68]
[20/03/19@07:22:15.376-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from returnValue [/tmp/pctinit12631002.p]
[20/03/19@07:22:15.376-0500] P-9896160 T-000001 3 4GL 4GLTRACE       Return from Main Block [/tmp/pctinit12631002.p]
```

**Comment by gquerret** [comment]
So it seems the error is about retrieving the security policies. So do you use a different `-U` and `-P` when you generate the incremental DF file without PCT ?

**Comment by hutcj** [comment]
I'm not familiar with `-U` and `-P`, but my test using the data dictionary was not the same as the PCT task I realized. I am using single-user and read-only mode in the PCT task, but used defaults on the data dictionary. I tried dumping an incremental df from the data dictionary using the `-RO` and `-1` options. I am getting errors like "Database must not be READ-ONLY (15001)" - why does the database need write access if it's just creating an incremental df? Should I not be using read-only and single-user?

**Comment by hutcj** [comment]
If I take out the readOnly option from the PCT task, incremental dump is successful.

**Comment by gquerret** [comment]
Interesting, I don't know why read-only is not possible for an incremental dump.
On the PCT side of things, I'll try to see why this message is not visible in the output.

**Comment by hutcj** [comment]
Ok, thanks for the help. I'm working on an OE database management program with groovy & PCT. With this issue resolved, I'll have the create, status, upgrade, and dump tasks complete.

**Comment by stefandrissen** [comment]
````
prodict/sec/_sec-pol-util.cls

USING Progress.Security.DB.* .

METHOD PRIVATE VOID getEpolicyObj (INPUT cDbName AS CHAR):
   DEFINE VARIABLE lOk AS LOGICAL     NO-UNDO.
   DEFINE VARIABLE cOrig AS CHAR      NO-UNDO.

    myEPolicy = NEW EncryptionPolicy(cDbName).

  ...
````
Throws error 15001 when the database is read only
````
Database must not be READ-ONLY (15001)

The EncryptionPolicy object may only be used with a writable Database
````
So it seems that while Progress fixed [this bug](https://knowledgebase.progress.com/articles/Article/000039148) for the normal dump, they forgot to fix the incremental dump.

prodict/dump/_dmpsddl.p first checks if encryption is enabled:
````
        CREATE BUFFER hBuffer2 FOR TABLE "DICTDB._database-feature" NO-ERROR.
        IF VALID-HANDLE(hBuffer2) THEN DO:
          hBuffer2:FIND-FIRST("WHERE _database-feature._dbfeature_name = ~'encryption~'",
                             NO-LOCK) NO-ERROR.
	  IF hBuffer2:AVAILABLE AND hBuffer2::_dbfeature_enabled EQ "1" THEN 
                myEPolicy = NEW prodict.sec._sec-pol-util(). 
````

Whereas prodict/dump/_dumpincr.p checkEPolicy only checks error 14889:
````
        myEPolicy[1] = NEW prodict.sec._sec-pol-util(LDBNAME("DICTDB")).
        CATCH ae AS PROGRESS.Lang.AppError:
           /* if encryption is not enabled, we simply ignore it */
            IF ae:GetMessageNum(1) NE 14889 THEN
               cMsg[1] = "Database " + LDBNAME("DICTDB") + " : " + ae:GetMessage(1).
            DELETE OBJECT ae.
        END CATCH.
````

**Comment by gquerret** [comment]
@stefandrissen  Thanks for the detailed information !
I'll report to tech support in case you didn't already report it.

**Comment by gquerret** [comment]
Reported to tech support
