### ISSUE TITLE
ABLUnit crashes with unhandled exception

### ISSUE THREAD

**Issue by upstyla** [Riverside-Software/pct#425]
### Subject of the issue
ABLUnit crashes with unhandled exception:

Extract from log file:

```
RUN ABLUnitCore.p
QUIT statement found
Exit code : 0

Unbehandelte Ausnahme: System.Runtime.InteropServices.SEHException: Eine externe Komponente hat eine Ausnahme ausgelöst.
   bei _CxxThrowException(Void* , _s__ThrowInfo* )
   bei Progress.ClrBridge.BrgTypeInspector.Inspect(BrgTypeInspector* , SByte* A_0)

BUILD FAILED
C:\workspaceOE12\NewChoice\build.xml:913: ABLUnit returned: -1073741819
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:645)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:497)
	at com.phenix.pct.PCTRun.execute(PCTRun.java:421)
	at com.phenix.pct.ABLUnit.execute(ABLUnit.java:202)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

### Your environment
* Operating system and version
Windows 10 
* OpenEdge version
OpenEdge Release 12.2.1 as of Thu Jul 16 19:02:21 EDT 2020
* Ant version
Apache Ant(TM) version 1.10.7 compiled on September 1 2019
* PCT version
pct-215-master-cd37c2f16888207e049462f2f84f302c4680dc9b

### Actual behaviour
When I run my ant script everything works fine up to the point ABLUnit. Here it seems as if the unit tests are being run cleanly and it looks like PCT cannot read the result. The Result.xml is completely created. All tests passed without errors. But it will abort with Exit Code : 0 and an unhandled exception. After that the build fail.

### Expected behaviour
When I run the same script with OpenEdge 11.7.4 everything works fine.

### Steps to reproduce
Tell us how to reproduce this issue.

**Comment by gquerret** [comment]
Return value `-1073741819` (or any large negative value) means that the OpenEdge session crashed, so you should have a protrace file available. Only Progress can fix this kind of issue, as it's a problem in the AVM. The protrace file might help tech support.

**Comment by gquerret** [comment]
PS: the `QUIT statement found` message in the logs indicates that you've reached the end of the ABLUnit session, and that the crash occured during clean up. So it definitely sounds like a Progress bug.

**Comment by upstyla** [comment]
Ok, thanks for the help, then I'll contact Progress TechSupport.
