### ISSUE TITLE
PCTProxygen task is failing with Openedge 12.1 JDK upgrade

### ISSUE THREAD

**Issue by ghost** [Riverside-Software/pct#427]
### Subject of the issue
From Openedge 12.1 onwards, we have stopped shipping java in DLC. And also started supporting JDK 11.x.  With this upgrade, 
PCTProxygen task is failing to generate proxies.

### Your environment
* Operating system and version : Windows 10 , Linux, AIX, Solaries
* OpenEdge version 12.1 and higher releases
* Ant version :1.10.5
* PCT version : PCT v212 and higher releases

### Actual behaviour
Instead of generating the proxies, following exception is thrown:

```
Apache Ant(TM) version 1.10.5 compiled on July 10 2018
Buildfile: C:\workspace\121\Aug2nd_1\proxy\build.xml
parsing buildfile C:\workspace\121\Aug2nd_1\proxy\build.xml with URI = file:/C:/workspace/121/Aug2nd_1/proxy/build.xml
Project base dir set to: C:\workspace\121\Aug2nd_1\proxy
parsing buildfile jar:file:/C:/121/Progress/OpenEdge/oeide/eclipse/plugins/org.apache.ant_1.10.5.v20180808-0324/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/121/Progress/OpenEdge/oeide/eclipse/plugins/org.apache.ant_1.10.5.v20180808-0324/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
[property] Loading Environment env.
Build sequence for target(s) `run' is [build, run]
Complete build sequence is [build, run, ]
build:
[PCTCompile] OpenEdge version found : OpenEdge Release 12.1ALPHA as of Fri Aug  2 19:03:02 EDT 2019
[PCTCompile] Using object : com.phenix.pct.ProgressV12
[PCTCompile] OpenEdge version found : OpenEdge Release 12.1ALPHA as of Fri Aug  2 19:03:02 EDT 2019
[PCTCompile] Using object : com.phenix.pct.ProgressV12
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] cpstream is not defined. You may have problems if file names have characters outside of ASCII range. You really should define it !
[PCTCompile] Current OS is Windows 10
[PCTCompile] Setting environment variable: DLC=C:\121\Progress\OpenEdge
[PCTCompile] Executing 'C:\121\Progress\OpenEdge\bin\_progres.exe' with arguments:
[PCTCompile] '-b'
[PCTCompile] '-q'
[PCTCompile] '-param'
[PCTCompile] 'C:\Users\rdhavala\AppData\Local\Temp\pct_params246381018.txt'
[PCTCompile] '-p'
[PCTCompile] 'C:\Users\rdhavala\AppData\Local\Temp\pctinit32712358.p'
[PCTCompile] 
[PCTCompile] The ' characters around the executable and arguments are
[PCTCompile] not part of the command.
[PCTCompile] PROPATH : C:\Users\rdhavala\AppData\Local\Temp\pctcomp125224618,C:\Users\rdhavala\AppData\Local\Temp\pct178717914.pl,.,C:\121\Progress\OpenEdge\tty,C:\121\Progress\OpenEdge\tty\ablunit.pl,C:\121\Progress\OpenEdge\tty\adecomm.pl,C:\121\Progress\OpenEdge\tty\adecomp.pl,C:\121\Progress\OpenEdge\tty\adeedit.pl,C:\121\Progress\OpenEdge\tty\adeshar.pl,C:\121\Progress\OpenEdge\tty\dataadmin.pl,C:\121\Progress\OpenEdge\tty\OpenEdge.BusinessLogic.pl,C:\121\Progress\OpenEdge\tty\OpenEdge.Core.pl,C:\121\Progress\OpenEdge\tty\OpenEdge.ServerAdmin.pl,C:\121\Progress\OpenEdge\tty\prodict.pl,C:\121\Progress\OpenEdge,C:\121\Progress\OpenEdge\bin
[PCTCompile] RUN pct/pctCompile.p
[PCTCompile] Switching to fileset C:\workspace\121\Aug2nd_1\proxy
[PCTCompile] Compiling custom.p in directory C:\workspace\121\Aug2nd_1\proxy TO C:\workspace\121\Aug2nd_1\proxy/
[PCTCompile] Compiling test.p in directory C:\workspace\121\Aug2nd_1\proxy TO C:\workspace\121\Aug2nd_1\proxy/
[PCTCompile] 2 file(s) compiled
[PCTCompile] Exit code : 0
run:
[PCTProxygen] OpenEdge version found : OpenEdge Release 12.1ALPHA as of Fri Aug  2 19:03:02 EDT 2019
[PCTProxygen] Using object : com.phenix.pct.ProgressV12
[PCTProxygen] Generating proxies from C:\workspace\121\Aug2nd_1\proxy\test.xpxg
[PCTProxygen] Executing 'C:\121\Progress\OpenEdge\jdk\bin\java.exe' with arguments:
[PCTProxygen] '-DInstall.Dir=C:\121\Progress\OpenEdge'
[PCTProxygen] '-DProxyGen.LeaveProxyFiles=no'
[PCTProxygen] '-DXPXGFile=C:\workspace\121\Aug2nd_1\proxy\test.xpxg'
[PCTProxygen] '-classpath'
[PCTProxygen] 'C:\121\Progress\OpenEdge\java\ext\soap.jar;C:\121\Progress\OpenEdge\java\ext\wsdl4j.jar;C:\121\Progress\OpenEdge\java\ext\xercesImpl.jar;C:\121\Progress\OpenEdge\java\ext\xmlParserAPIs.jar;C:\121\Progress\OpenEdge\java\messages.jar;C:\121\Progress\OpenEdge\java\progress.jar;C:\121\Progress\OpenEdge\java\proxygen.zip'
[PCTProxygen] 'com.progress.open4gl.proxygen.Batch'
[PCTProxygen] 
[PCTProxygen] The ' characters around the executable and arguments are
[PCTProxygen] not part of the command.
[PCTProxygen] Output redirected to C:\Users\rdhavala\AppData\Local\Temp\pxg20697470.out
[PCTProxygen] Setting environment variable: DLC=C:\121\Progress\OpenEdge

BUILD FAILED
C:\workspace\121\Aug2nd_1\proxy\build.xml:17: Unable to parse output
               at com.phenix.pct.PCTProxygen.executeProxygen(PCTProxygen.java:238)
               at com.phenix.pct.PCTProxygen.execute(PCTProxygen.java:176)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:498)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.Target.performTasks(Target.java:470)
               at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
               at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
               at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
               at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
               at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
               at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:460)
               at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:142)
Caused by: java.io.FileNotFoundException: C:\Users\rdhavala\AppData\Local\Temp\pxg20697470.out (The system cannot find the file specified)
               at java.io.FileInputStream.open0(Native Method)
               at java.io.FileInputStream.open(FileInputStream.java:195)
               at java.io.FileInputStream.<init>(FileInputStream.java:138)
               at java.io.FileReader.<init>(FileReader.java:72)
               at com.phenix.pct.PCTProxygen.executeProxygen(PCTProxygen.java:221)
               ... 17 more

Total time: 628 milliseconds
```

### Expected behaviour
Proxies has to be generated.

### Steps to reproduce
Please take the attached project and use the ant task to reproduce the issue.
[testProxy.zip](https://github.com/Riverside-Software/pct/files/5365091/testProxy.zip)

**Comment by gquerret** [comment]
Support for 12.1 came with [version 213](https://github.com/Riverside-Software/pct/releases/tag/V213), please upgrade to this version (or better, to version 215). You also seem to use 12.1 **ALPHA**.

**Comment by ghost** [comment]
Hi,

This is Ramadevi Dhavala from Progress software development private limited. 12.1 is the version where we started seeing the issue. The issue remains same with  Openedge 12.2.x, 12.3 and 12.4 versions (few not yet released) when tried against PCT 215. Are there any plans to fix this issue? please let us know. 

Thanks,
Ramadevi

**Comment by gquerret** [comment]
The stack trace contains:
```
               at com.phenix.pct.PCTProxygen.executeProxygen(PCTProxygen.java:238)
```
Line 238 is not executable in v215, so you're using v212 or earlier.

**Comment by ghost** [comment]
Yes I agree. The stack trace I have provided it old. But the test is failing for us with PCT v215 as well. Do you have a test from your side? Is it passing ?

**Comment by gquerret** [comment]
Unit test is successful on 12.2: https://ci.rssw.eu/job/PCT/job/master/lastSuccessfulBuild/artifact/emailable-report-12.2-Win.html#m306
Source code for this test: https://github.com/Riverside-Software/pct/tree/master/tests/PCTProxygen/test6
Note that the XPXG file has to be modified during the test, because the location of the Java compiler is read from the file (instead of reading it from $DLC/properties/java.properties). Many values also contain absolute paths when XPXG file is created from the Windows Proxy Generator tool. For example, your test case contains:
* WorkDir: C:\120\OpenEdge\WRK\
* JavaCompiler: C:\JAVA\JDK18~1.0_2\bin\javac.exe
* ProPath: C:\120\OpenEdge\WRK\ (multiple times)
* And declares a procedure custom.p while the procedure file name is test.p

The absolute paths are likely to be invalid on your CI server, this could lead to a failure.

**Comment by ghost** [comment]
Thank you. Let me give a try with latest version and get back to you.

**Comment by gquerret** [comment]
@rdhavala Does it work with the latest version ?
