### ISSUE TITLE
Suggestion: add tasks to manage Pacific Appserver instances and ABL web applications

### ISSUE THREAD

**Issue by gabsoftware** [Riverside-Software/pct#429]
### Subject of the issue
PCT is already very helpful, it would be even more helpful in a continuous integration process if there were some tasks related to mananing Pacific AppServer instances. Including:
- Creating, configuring, deleting PAS instances
- Deploying ABL applications, Web applications and Web app services
- Creating an ABL Web Application .war file from project source code would also be nice

### Your environment
* CentOS 8
* OpenEdge version 12.2
* Ant version 1.10.5
* PCT version latest available

**Comment by stefandrissen** [comment]
You're probably already doing this, but just in case your not, I handled this by creating Ant macrodefs for:

- pasman-create
- pasman-pasoestart 
- pasman-stop
- pasman-delete

Which all call a pasman macrodef that execs pasman.

````
	<!-- pasman - progress application server manager -->

	<macrodef name="pasman">
		<attribute name="oe" />
		<attribute name="action" />
		<attribute name="verbose" default="false" />
		<attribute name="copy-war" default="false" />
		<attribute name="http-port" default="" />
		<attribute name="https-port" default="" />
		<attribute name="shutdown-port" default="" />
		<attribute name="instance" default="" />
		<attribute name="app" default="" />
		<attribute name="confirm-delete" default="false" />
		<attribute name="base-path" default="" />
		<attribute name="war-file" default="" />
		<attribute name="failonerror" default="true" />

		<sequential xmlns:if="ant:if" xmlns:unless="ant:unless">

			<local name="dlc" />
			<property name="dlc" value="c:\progress\oe@{oe}" if:set="os.windows" />
			<property name="dlc" value="/opt/progress/oe@{oe}" if:set="os.linux" />

			<set-bat-extension />

			<exec executable="${dlc}/bin/pasman${bat}" failonerror="@{failonerror}">
				<env key="DLC" value="${dlc}" />

				<arg value="@{action}" />

				<!-- -v -->
				<arg line="-v" if:true="@{verbose}" />
				<!-- -f -->
				<arg line="-f" if:true="@{copy-war}" />
				<!-- -p http-port -->
				<arg line="-p @{http-port}" unless:blank="@{http-port}" />
				<!-- -P https-port -->
				<arg line="-P @{https-port}" unless:blank="@{https-port}" />
				<!-- -s shutdown-port -->
				<arg line="-s @{shutdown-port}" unless:blank="@{shutdown-port}" />
				<!-- -I <alias> -->
				<arg line="-I @{instance}" unless:blank="@{instance}" />
				<!-- -a app_name -->
				<arg line="-a @{app}" unless:blank="@{app}" />
				<!-- -y -->
				<arg line="-y" if:true="@{confirm-delete}" />
				<!-- base path -->
				<arg value="@{base-path}" unless:blank="@{base-path}" />
				<!-- <war-file-path> -->
				<arg value="${dlc}\servers\pasoe\extras\@{war-file}" unless:blank="@{war-file}" />
				<!-- [abl-app-name] -->
				<arg value="@{app}" unless:blank="@{app}" />

			</exec>

		</sequential>

	</macrodef>
````

pasman-create also uses macrodef oeprop which execs oeprop.

````
	<!-- oeprop - openedge properties -->

	<macrodef name="oeprop">
		<attribute name="oe" />
		<attribute name="instance.dir" />
		<attribute name="property" />
		<attribute name="value" />
		<attribute name="failonerror" default="true" />

		<sequential xmlns:if="ant:if" xmlns:unless="ant:unless">

			<set-bat-extension />

			<local name="dlc" />
			<property name="dlc" value="c:\progress\oe@{oe}" if:set="os.windows" />
			<property name="dlc" value="/opt/progress/oe@{oe}" if:set="os.linux" />

			<!-- relative location is resulting in: CreateProcess error=2, The system cannot find the file specified -->
			<local name="oeprop" />
			<property name="oeprop" location="@{instance.dir}/bin/oeprop${bat}" />

			<exec executable="${oeprop}" failonerror="@{failonerror}">
				<env key="DLC" value="${dlc}" />

				<!-- +name=value -->
				<arg value="+@{property}=@{value}" />

			</exec>

		</sequential>

	</macrodef>
````

**Comment by gabsoftware** [comment]
Thanks Stefan, I am currently setting up continuous integration for a PAS web application. I didn't have your macros.
I am currently facing a problem with the missing restgen utility in v12.x releases of OpenEdge used to create a Paar file.

**Comment by stefandrissen** [comment]
> I am currently facing a problem with the missing restgen utility in v12.x releases of OpenEdge used to create a Paar file.

Sorry, can't help you with restgen since we use the web handler for handling rest web services.

**Comment by gabsoftware** [comment]
We are migrating to web handlers but mostly we used the Rest services.

I found https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/pdsoe%2Fpackaging-rest-services.html%23 as a replacement for restgen, but it still doesn't work.

Here's a sample build file (for OpenEdge 12.2):

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="ABLWebApp" default="main" basedir=".">

    <condition property="windowsos" value="true">
        <os family="windows" />
    </condition>
    <condition property="linuxos" value="true">
        <os family="unix" />
    </condition>

    <property name="dlc.dir.win" value="C:\Progress\122" />
    <property name="dlc.dir.unx" value="/usr/dlc122" />

    <target name="setWindowsDlcDir" if="windowsos">
        <property name="dlc.dir" value="${dlc.dir.win}" />
        <property name="dlc.java.dir" value="${dlc.dir}\java" />
        <property name="src.dir" value="${basedir}" />
        <property name="dest.dir" value="${basedir}\build" />
    </target>

    <target name="setUnixDlcDir" if="linuxos">
        <property name="dlc.dir" value="${dlc.dir.unx}" />
        <property name="dlc.java.dir" value="${dlc.dir}/java" />
        <property name="src.dir" value="${basedir}" />
        <property name="dest.dir" value="${basedir}/build" />
    </target>

    <target name="defineProperties" depends="setWindowsDlcDir,setUnixDlcDir">
        <property name="app.name" value="Toutatis" />
    </target>
    
    <target name="taskdef">
        <taskdef resource="com/progress/openedge/pdt/ant/ablwebapp/ablwebapps.properties">
            <classpath>
                <pathelement location="${dlc.java.dir}/ant-ablwebapp.jar" />
                
                <!-- ABLWebApp Dependencies -->
                <pathelement location="${dlc.java.dir}/ant-libs/ablwebapp.jar" />
                <pathelement location="${dlc.java.dir}/ant-libs/ablwebapp-dependencies.jar" />
                
                <!-- CodeModel Dependencies -->
                <pathelement location="${dlc.java.dir}/ant-libs/codemodel-dependencies.jar" />
                
                <!-- AST and its Dependencies -->
                <pathelement location="${dlc.java.dir}/ant-libs/ast.jar" />
                <pathelement location="${dlc.java.dir}/ant-libs/ast-dependencies.jar" />
                
                <!-- Additional deps -->
                <pathelement location="${dlc.java.dir}/ant-libs/velocity-1.7.jar" />
                <pathelement location="${dlc.java.dir}/ant-libs/velocity-1.7-dep.jar" />
                <pathelement location="${dlc.java.dir}/ant-libs/1padapters-restExpose.jar" />
                <pathelement location="${dlc.java.dir}/1padapters-util.jar" />
                <pathelement location="${dlc.java.dir}/1padapters-idl.jar" />
                <pathelement location="${dlc.java.dir}/ext/jettison-1.4.0.jar" />
            </classpath>
        </taskdef>
    </target>

    <target name="main" depends="defineProperties,taskdef">      
        <ABLWebAppPackage srcdir="${src.dir}"
                          dlc="${dlc.dir}"
                          verbose="false"
                          isIncremental="false"
                          webAppName="${app.name}"
                          destdir="${dest.dir}" />

        <PaarGeneration srcdir="${src.dir}"
                        dlc="${dlc.dir}"
                        verbose="false"
                        destdir="${dest.dir}\${app.name}" />
    </target>
    
</project>
```

Result:
```
proenv>ant -buildfile build_pasoe.xml main
Buildfile: C:\Dev12\application\build_pasoe.xml

setWindowsDlcDir:

setUnixDlcDir:

defineProperties:

taskdef:

main:
[ABLWebAppPackage] Started executing ABLWebAppPackage
[ABLWebAppPackage] Validating Task Properties
[ABLWebAppPackage] Executing ABLWebApp packaging task
[ABLWebAppPackage] com.progress.caf.idl.IDLException: IDLCoreException: faultCode=CONFIGURATION_ERROR: Problem instantiating a IDLCoreFactory implementation using factory impl name 'com.progress.caf.idl.internal.DOMIDLFactory'
[ABLWebAppPackage]      at com.progress.caf.idl.internal.IDLFactory.<init>(IDLFactory.java:49)
[ABLWebAppPackage]      at com.progress.caf.idl.manager.IDLManager.init(IDLManager.java:59)
[ABLWebAppPackage]      at com.progress.tools.caf.adapter.rest.expose.core.model.ToolingIDLHandler.<init>(ToolingIDLHandler.java:47)
[ABLWebAppPackage]      at com.progress.tools.caf.adapter.rest.expose.ui.RestExposeArchiveHandler.visit(RestExposeArchiveHandler.java:105)
[ABLWebAppPackage]      at com.progress.tools.caf.archiver.model.visitor.ArchiverCAFModelCompositeVisitor.visit(ArchiverCAFModelCompositeVisitor.java:42)
[ABLWebAppPackage]      at com.progress.tools.caf.core.internal.model.impl.logical.ServiceImpl.accept(ServiceImpl.java:309)
[ABLWebAppPackage]      at com.progress.tools.caf.archiver.model.impl.CAFArchiver.startVisiting(CAFArchiver.java:275)
[ABLWebAppPackage]      at com.progress.tools.caf.archiver.model.impl.CAFArchiver._archive(CAFArchiver.java:159)
[ABLWebAppPackage]      at com.progress.tools.caf.archiver.model.impl.CAFArchiver.archive(CAFArchiver.java:67)
[ABLWebAppPackage]      at com.progress.openedge.pdt.rest.util.PAARGenerator.generatePAARFiles(PAARGenerator.java:98)
[ABLWebAppPackage]      at com.progress.openedge.pdt.rest.util.PAARGenerator.generatePAARFilesForWar(PAARGenerator.java:193)
[ABLWebAppPackage]      at com.progress.openedge.pdt.ablservice.util.WebArchiveGenerator.generateWar(WebArchiveGenerator.java:200)
[ABLWebAppPackage]      at com.progress.openedge.pdt.ablservice.util.WebArchiveGenerator.generateWar(WebArchiveGenerator.java:119)
[ABLWebAppPackage]      at com.progress.openedge.pdt.ablwebapp.executor.ABLWebAppExecutorDelegate.executeWebAppPackage(ABLWebAppExecutorDelegate.java:82)
[ABLWebAppPackage]      at com.progress.openedge.pdt.ablwebapp.executor.ABLWebAppExecutorDelegate.execute(ABLWebAppExecutorDelegate.java:42)
[ABLWebAppPackage]      at com.progress.openedge.pdt.ablwebapp.executor.DefaultWebAppTaskExecutor.execute(DefaultWebAppTaskExecutor.java:57)
[ABLWebAppPackage]      at com.progress.openedge.pdt.ant.ablwebapp.tasks.AbstractPackageTask.execute(Unknown Source)
[ABLWebAppPackage]      at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[ABLWebAppPackage]      at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[ABLWebAppPackage]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ABLWebAppPackage]      at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ABLWebAppPackage]      at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
[ABLWebAppPackage]      at org.apache.tools.ant.Task.perform(Task.java:350)
[ABLWebAppPackage]      at org.apache.tools.ant.Target.execute(Target.java:449)
[ABLWebAppPackage]      at org.apache.tools.ant.Target.performTasks(Target.java:470)
[ABLWebAppPackage]      at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
[ABLWebAppPackage]      at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[ABLWebAppPackage]      at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[ABLWebAppPackage]      at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
[ABLWebAppPackage]      at org.apache.tools.ant.Main.runBuild(Main.java:830)
[ABLWebAppPackage]      at org.apache.tools.ant.Main.startAnt(Main.java:223)
[ABLWebAppPackage]      at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
[ABLWebAppPackage]      at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
[ABLWebAppPackage] Cleaning up temporary files...

BUILD FAILED
C:\Dev12\application\build_pasoe.xml:85: java.lang.NullPointerException: Cannot invoke "com.progress.caf.idl.internal.IDLFactory.newDescription()" because the return value of "com.progress.tools.caf.adapter.rest.expose.core.model.ToolingIDLHandler.getFactory()" is null
        at com.progress.tools.caf.adapter.rest.expose.ui.RestExposeArchiveHandler.visit(RestExposeArchiveHandler.java:106)
        at com.progress.tools.caf.archiver.model.visitor.ArchiverCAFModelCompositeVisitor.visit(ArchiverCAFModelCompositeVisitor.java:42)
        at com.progress.tools.caf.core.internal.model.impl.logical.ServiceImpl.accept(ServiceImpl.java:309)
        at com.progress.tools.caf.archiver.model.impl.CAFArchiver.startVisiting(CAFArchiver.java:275)
        at com.progress.tools.caf.archiver.model.impl.CAFArchiver._archive(CAFArchiver.java:159)
        at com.progress.tools.caf.archiver.model.impl.CAFArchiver.archive(CAFArchiver.java:67)
        at com.progress.openedge.pdt.rest.util.PAARGenerator.generatePAARFiles(PAARGenerator.java:98)
        at com.progress.openedge.pdt.rest.util.PAARGenerator.generatePAARFilesForWar(PAARGenerator.java:193)
        at com.progress.openedge.pdt.ablservice.util.WebArchiveGenerator.generateWar(WebArchiveGenerator.java:200)
        at com.progress.openedge.pdt.ablservice.util.WebArchiveGenerator.generateWar(WebArchiveGenerator.java:119)
        at com.progress.openedge.pdt.ablwebapp.executor.ABLWebAppExecutorDelegate.executeWebAppPackage(ABLWebAppExecutorDelegate.java:82)
        at com.progress.openedge.pdt.ablwebapp.executor.ABLWebAppExecutorDelegate.execute(ABLWebAppExecutorDelegate.java:42)
        at com.progress.openedge.pdt.ablwebapp.executor.DefaultWebAppTaskExecutor.execute(DefaultWebAppTaskExecutor.java:57)
        at com.progress.openedge.pdt.ant.ablwebapp.tasks.AbstractPackageTask.execute(Unknown Source)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
        at org.apache.tools.ant.Main.runBuild(Main.java:830)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 2 seconds
```

**Comment by gquerret** [comment]
> I am currently facing a problem with the missing restgen utility in v12.x releases of OpenEdge used to create a Paar file.

@gabsoftware Did you try https://github.com/Riverside-Software/pct/wiki/RestGen ?

@stefandrissen Thanks for the macros !

**Comment by gabsoftware** [comment]
> @gabsoftware Did you try https://github.com/Riverside-Software/pct/wiki/RestGen ?

@gquerret No, I swear I looked over PCT tasks to see if there were anything related to REST and I just missed the one task! Will try now.

**Comment by gabsoftware** [comment]
@gquerret `<RestGen>` gave me an error:

`<RestGen destFile="${dest.dir}/Application.paar" dlcHome="${dlc.dir}" projectDir="." services="ApplicationService" type="paar"/>`

```
  [RestGen] Erreur : impossible de trouver ou de charger la classe principale com.progress.rest.tools.WARGenerator
  [RestGen] Causé par : java.lang.ClassNotFoundException: com.progress.rest.tools.WARGenerator
  [RestGen] Java Result: 1
```

Note: adding  `includeJars="true"` does not change anything. And I don't have any rest directory in either Windows and Linux releases of OE12.2. Setting pdsHome does not change anything either.

**Comment by gabsoftware** [comment]
Fixed the Paar generation error by using different classpath than the one listed in the Progress documentation:

```
  <target name="taskdef">
    <echo>Task Definitions</echo>
    <taskdef resource="com/progress/openedge/pdt/ant/ablwebapp/ablwebapps.properties">
      <classpath>
        <fileset dir="${dlc.java.dir}">
          <include name="*.jar"/>
        </fileset>
        <fileset dir="${dlc.java.dir}/ant-libs">
          <include name="*.jar"/>
        </fileset>
        <fileset dir="${dlc.java.dir}/ext">
          <include name="*.jar"/>
        </fileset>
      </classpath>
    </taskdef>
  </target>
  <target depends="defineProperties,taskdef" name="main">
    <ABLWebAppPackage srcdir="${src.dir}"
                                        dlc="${dlc.dir}"
                                        verbose="false"
                                        isIncremental="false"
                                        webAppName="${app.name}"
                                        destdir="${dest.dir}" />
    <PaarGeneration srcdir="${src.dir}"
                    dlc="${dlc.dir}"
                    verbose="true"
                    destdir="${dest.dir}\${app.name}"
                    services="MyService" />
  </target>
```

**Comment by gabsoftware** [comment]
I successfully automated the compilation and deployment of an ABL web application on a Linux PAS. I could not get the RestGen task to work but I managed to use the PaarGeneration task from OpenEdge.

If it can help anyone, here's a sample Ant build.xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="main" name="MyAppABLWebApp">
  <description>Lance le build de MyApp</description>

  <buildnumber/>

  <property environment="env"/>

  <taskdef resource="PCT.properties"/>
  <typedef resource="types.properties"/>

  <condition property="windowsos" value="true">
    <os family="windows"/>
  </condition>
  <condition property="linuxos" value="true">
    <os family="unix"/>
  </condition>

  <PCTVersion />
  
  <DBConnectionSet id="localdb">
    <DBConnection dbName="database1" dbDir="mydbdir" />
    <DBConnection dbName="database2" dbDir="mydbdir" />    
    <DBConnection dbName="database3" dbDir="mydbdir" />
  </DBConnectionSet>

  <DBConnectionSet id="serverdb">
    <DBConnection dbName="/data/db/database1" dbPort="17201" hostName="mydberver.com" />
    <DBConnection dbName="/data/db/database2" dbPort="17301" hostName="mydberver.com" />    
    <DBConnection dbName="/data/db/database3" dbPort="17601" hostName="mydberver.com" />
  </DBConnectionSet>

  <property name="dlc.dir.win" value="C:\Progress\122"/>
  <property name="dlc.dir.unx" value="/usr/dlc122"/>
  <property name="wrk.dir"     value="${env.WRKDIR}"/>

  <target name="setWindowsDlcDir"
            if="windowsos">
    <property name="dlc.dir"      value="${dlc.dir.win}"/>
    <property name="dlc.java.dir" value="${dlc.dir}\java"/>
    <property name="src.dir"      value="${basedir}"/>
    <property name="dest.dir"     value="${basedir}\build"/>
    <property name="myapp.pasoe"  location="${env.WRKDIR}/myapp" />
  </target>

  <target name="setUnixDlcDir"
            if="linuxos">
    <property name="dlc.dir"      value="${dlc.dir.unx}"/>
    <property name="dlc.java.dir" value="${dlc.dir}/java"/>
    <property name="src.dir"      value="${basedir}"/>
    <property name="dest.dir"     value="${basedir}/build"/>
    <property name="myapp.pasoe"  location="${wrk.dir}/myapp" />
  </target>

  <target name="defineProperties"
       depends="setWindowsDlcDir,setUnixDlcDir">
    <property name="app.name" value="MyApp"/>
    <echo>dlc.dir      = ${dlc.dir}</echo>
    <echo>dlc.java.dir = ${dlc.java.dir}</echo>
    <echo>src.dir      = ${src.dir}</echo>
    <echo>dest.dir     = ${dest.dir}</echo>
  </target>
  
  <target name="taskdef">
    <echo>Task Definitions</echo>
    <taskdef resource="com/progress/openedge/pdt/ant/ablwebapp/ablwebapps.properties">
      <classpath>
        <fileset dir="${dlc.java.dir}">
          <include name="*.jar"/>
        </fileset>
        <fileset dir="${dlc.java.dir}/ant-libs">
          <include name="*.jar"/>
        </fileset>
        <fileset dir="${dlc.java.dir}/ext">
          <include name="*.jar"/>
        </fileset>
      </classpath>
    </taskdef>
  </target>

  <target name="cleanbuild">
    <delete dir="${dest.dir}"  />
  </target>

  <target name="init" depends="cleanbuild">
    <tstamp/>
    <mkdir dir="${dest.dir}" />
    <mkdir dir="${dest.dir}/AppServer" />
    <mkdir dir="${dest.dir}/WebServices" />
  </target>



  <target name="compile_myapp" depends="init,compile_myapp_cls,compile_myapp_p">
  </target>
  <target name="compile_myapp_cls">
    <PCTCompile destDir="${dest.dir}" dlcHome="${env.DLC}" paramFile="pct.pf" stopOnError="false" forceCompile="true" progPerc="10">
      <DBConnectionSet refid="serverdb" />
      <fileset dir="${src.dir}/src">
        <include name="**/*.cls" />
      </fileset>
      <propath>
        <pathelement path="${src.dir}/src"/>
        <pathelement path="${src.dir}/src/AppServer"/>
        <pathelement path="${src.dir}/src/WebServices"/>
        <pathelement path="${dlc.dir}/tty/netlib/OpenEdge.Net.pl"/>
      </propath>
    </PCTCompile>
  </target>
    <target name="compile_myapp_p">
    <PCTCompile destDir="${dest.dir}" dlcHome="${env.DLC}" paramFile="pct.pf" stopOnError="false" forceCompile="true" progPerc="10">
      <DBConnectionSet refid="serverdb" />
      <fileset dir="${src.dir}/src">
        <include name="**/*.p"   />
        <include name="**/*.t" />
      </fileset>
      <propath>
        <pathelement path="${src.dir}/src"/>
        <pathelement path="${src.dir}/src/AppServer"/>
        <pathelement path="${src.dir}/src/WebServices"/>
        <pathelement path="${dlc.dir}/tty/netlib/OpenEdge.Net.pl"/>
      </propath>
    </PCTCompile>
  </target>

  <target name="buildablwebpackage">
    <ABLWebAppPackage destdir="${dest.dir}"
                          dlc="${dlc.dir}"
                isIncremental="false"
                     services="WebServiceA,WebServiceB,WebServiceC"
                       srcdir="${src.dir}"
                      verbose="true"
                   webAppName="ROOT"/>
  </target>

  <target name="buildpaar">
    <PaarGeneration srcdir="${src.dir}"
                       dlc="${dlc.dir}"
                   verbose="true"
                   destdir="${dest.dir}"
                  services="MyAppRestService" />
  </target>

  <target name="buildwebapp" depends="buildablwebpackage,buildpaar"></target>

  <target name="deploywebapp" depends="deploywebappwin,deploywebappunx">
  </target>

  <target name="deploywebappwin" if="windowsos">
    <exec executable="cmd" osfamily="windows">
      <arg value="/c"/>
      <arg value="${myapp.pasoe}\bin\deployREST.bat" />
      <arg value="MyAppRestService" />
      <arg value="ROOT" />
      <arg value="-undeploy" />
    </exec>
    <exec executable="cmd" osfamily="windows">
      <arg value="/c"/>
      <arg value="${myapp.pasoe}\bin\tcman.bat" />
      <arg value="undeploy" />
      <arg value="-u" />
      <arg value="tomcat:tomcat" />
      <arg value="ROOT" />
    </exec>
    <exec executable="cmd" osfamily="windows">
      <arg value="/c"/>
      <arg value="${myapp.pasoe}\bin\tcman.bat" />
      <arg value="deploy" />
      <arg value="build\ROOT.war" />
    </exec>
    <exec executable="cmd" osfamily="windows">
      <arg value="/c"/>
      <arg value="${myapp.pasoe}\bin\deployREST.bat" />
      <arg value="build\MyAppRestService.paar" />
      <arg value="ROOT" />
    </exec>
    <exec executable="cmd" osfamily="windows">
      <arg value="/c"/>
      <arg value="${myapp.pasoe}\bin\tcman.bat" />
      <arg value="stop" />
    </exec>
    <exec executable="cmd" osfamily="windows">
      <arg value="/c"/>
      <arg value="${myapp.pasoe}\bin\tcman.bat" />
      <arg value="start" />
    </exec>
  </target>

  <target name="deploywebappunx" if="linuxos">
    <exec executable="${myapp.pasoe}/bin/deployREST.sh" osfamily="unix">
      <arg value="MyAppRestService" />
      <arg value="ROOT" />
      <arg value="-undeploy" />
    </exec>
    <exec executable="${myapp.pasoe}/bin/tcman.sh" osfamily="unix">
      <arg value="undeploy" />
      <arg value="-u" />
      <arg value="tomcat:tomcat" />
      <arg value="ROOT" />
    </exec>
    <exec executable="${myapp.pasoe}/bin/tcman.sh" osfamily="unix">
      <arg value="deploy" />
      <arg value="build/ROOT.war" />
    </exec>
    <exec executable="${myapp.pasoe}/bin/deployREST.sh" osfamily="unix">
      <arg value="build/MyAppRestService.paar" />
      <arg value="ROOT" />
    </exec>
    <exec executable="${myapp.pasoe}/bin/tcman.sh" osfamily="unix">
      <arg value="stop" />
    </exec>
    <exec executable="${myapp.pasoe}/bin/tcman.sh" osfamily="unix">
      <arg value="start" />
    </exec>
  </target>

  <target name="cleanpasoe">
    <delete includeemptydirs="true">
      <fileset dir="${myapp.pasoe}/openedge" defaultexcludes="false">
        <include name="**/*"/>
        <exclude name="**/schema/*"/>
      </fileset>
    </delete>
  </target>

  <target name="copytopasoe" depends="cleanpasoe">

    <mkdir dir="${myapp.pasoe}/openedge/AppServer" />
    <copy todir="${myapp.pasoe}/openedge/AppServer">
      <fileset dir="${dest.dir}/AppServer" />
    </copy>

    <mkdir dir="${myapp.pasoe}/openedge/WebServices" />
    <copy todir="${myapp.pasoe}/openedge/WebServices">
      <fileset dir="${dest.dir}/WebServices" />
    </copy>

  </target>

  <target name="main"
      depends="defineProperties,taskdef,compile_myapp,buildwebapp,deploywebapp,copytopasoe">
  </target>

</project>
```

**Comment by gquerret** [comment]
Note that you can use Groovy if you want to write deployment scripts. While build script easily accomodate the target system of Ant, deployment almost always require some conditional logic, which is extremely difficult to maintain with Ant. Ant contrib should be avoided like plague (or covid-19).

**Comment by gabsoftware** [comment]
@gquerret Good idea !
How would you define a DBConnectionSet in a build.gradle to make it available in other tasks by using refid?

**Comment by gquerret** [comment]
> How would you define a DBConnectionSet in a build.gradle to make it available in other tasks by using refid?

Code for a DBConnection, DBConnectionSet will be similar:
```
def ant = new AntBuilder()
ant.typedef (name: 'DBConnection', classname: 'com.phenix.pct.PCTConnection')
ant.taskdef (name: 'PCTRun', classname: 'com.phenix.pct.PCTRun')

def db1 = ant.DBConnection(dbName: 'foo', id: 'xyz');
ant.PCTRun (procedure: 'xxx.p') {
  dbConnection(refid: 'db1')
}
```

I'll be doing a short session about Groovy during the [PUG Challenge](https://pugchallenge.eu), feel free to register !

**Comment by gabsoftware** [comment]
Ah, I do not have the 3 first lines of your example in my build.gradle. Are they absolutely necessary?
What I currently have instead of these 3 lines:
```
String pctjar = System.getenv( "ANT_HOME" ) + "/lib/PCT.jar"
ant.taskdef( resource: "PCT.properties"  , classpath: pctjar )
ant.typedef( resource: "types.properties", classpath: pctjar )
ant.taskdef( resource: "com/progress/openedge/pdt/ant/ablwebapp/ablwebapps.properties" ) {
    ant.classpath() {
        ant.fileset( dir: dlc_java_dir ) {
            ant.include( name: "*.jar" )
        }
        ant.fileset( dir: "${dlc_java_dir}/ant-libs" ) {
            ant.include( name: "*.jar" )
        }
        ant.fileset( dir: "${dlc_java_dir}/ext" ) {
            ant.include( name: "*.jar" )
        }
    }
}
```
Then I do:

```
DBConnectionSet( id: "dbcon" ) {
    DBConnection( dbName: "/data/db/db1", dbPort: "17100", hostName: "mydbserver.com" )
    DBConnection( dbName: "/data/db/db2", dbPort: "17101", hostName: "mydbserver.com" )
    DBConnection( dbName: "/data/db/db3", dbPort: "17102", hostName: "mydbserver.com" )
}
```

```
ant.PCTCompile( ... ) {
    DBConnectionSet( refid: "dbcon" )  <=== Throws an error saying no DBConnectionSet with id "dbcon" exists
    ...
}
```

**Comment by gabsoftware** [comment]
Okay, but it does not work as expected with DBConnectionSet.

```
ant.DBConnectionSet( id: "dbcon" ) {
    DBConnection( dbName: "/data/db/db1", dbPort: "17100", hostName: "mydbserver.com" )
    DBConnection( dbName: "/data/db/db2", dbPort: "17101", hostName: "mydbserver.com" )
    DBConnection( dbName: "/data/db/db3", dbPort: "17102", hostName: "mydbserver.com" )
}
```

Then in a Gradle task:
```
ant.PCTCompile( ... ) {
    DBConnectionSet( refid: "dbcon" )
    ...
}
```

Output:
`dbcon doesn't denote a DBConnectionSet`

I tried to do as well:
```
def dbcon = ant.DBConnectionSet() {
    DBConnection( dbName: "/data/db/db1", dbPort: "17100", hostName: "mydbserver.com" )
    DBConnection( dbName: "/data/db/db2", dbPort: "17101", hostName: "mydbserver.com" )
    DBConnection( dbName: "/data/db/db3", dbPort: "17102", hostName: "mydbserver.com" )
}
```
But same error.

**Comment by gabsoftware** [comment]
Very weird, the only way I can reuse a DBConnectionSet by refid in subsequent PCTCompile tasks is to wrap their definition in an empty PCTCompile task:

```
        ant.PCTCompile {
            DBConnectionSet( id: "dbcon" ) {
                DBConnection( dbName: "/data/db/db1", dbPort: "17100", hostName: "mydbserver.com" )
                DBConnection( dbName: "/data/db/db2", dbPort: "17101", hostName: "mydbserver.com" )
                DBConnection( dbName: "/data/db/db3", dbPort: "17102", hostName: "mydbserver.com" )
            }
        }
```
I do not understand why this works, and why it doesn't work without the empty PCTCompile wrapper.

**Comment by gquerret** [comment]
This works:

```
def ant = new AntBuilder()
ant.taskdef (resource: 'PCT.properties')
ant.typedef (resource: 'types.properties')

def db1 = ant.DBConnection(dbName: 'db1', id: 'xxx1');
def db2 = ant.DBConnection(dbName: 'db2', id: 'xxx2');
def dbset1 = ant.DBConnectionSet(id: 'set1') {
  dbConnection(refid: 'xxx1')
  dbConnection(refid: 'xxx2')
}
ant.PCTRun (procedure: 'xxx.p') {
  DbConnectionSet(refid: 'set1')
  env(key: 'TERM', value: 'xterm')
}
```
