### ISSUE TITLE
NPE from ABLDuck task - public property w/private setter

### ISSUE THREAD

**Issue by PeterJudgeZA** [Riverside-Software/pct#479]
**Describe the bug**
NPE raised when generating documentation .

If a class has a public property with a PRIVATE set, a NPE is raised. If the class below is used as an input to the ABLDuck task, the NPE is raised.
Note that in the Headers class below, there is also a property with no set implementation; this does not cause the NPE.

````
using Progress.Lang.Object.

class Headers: 
   
    define public property Count as integer no-undo 
    get().
        return 42.
    end.

    define public property IsReadOnly as logical no-undo get. private set.
    /**
        Construct an empty Headers collection.
    */
    constructor Headers().
    end.

    method public Object extent ToArray():
    end method.
end class.
````

``C:\devarea\psc-github\ablapidoc\build.xml:51: java.lang.NullPointerException: Cannot invoke "eu.rssw.rcode.GetSetModifier.toString()" because "property.setModifier" is null`` 

**To Reproduce**
Snippet from build.xml
````xml
    <taskdef resource="PCT.properties" />
    <typedef resource="types.properties" />
    <taskdef resource="extras115.properties" />

    <target name="ablduck-all" >
        <mkdir dir="${build.root}/html" />
        
        <ABLDuck destDir="${build.root}/html" title="OpenEdge API Code Documentation">
            <fileset dir="${build.root}/preprocess">
                <include name="Headers.cls"/>
            </fileset>
        </ABLDuck>

    </target>
````

**Expected behavior**
No NPE, documentation produced, happy dev

**Environment**
- Windows 10 64-bit
- OpenEdge 12.5+
- PCT 221

**Additional context**
Build log (with -v) is attached as [ant.log](https://github.com/Riverside-Software/pct/files/8497548/ant.log)

Error stack
````
  [ABLDuck] Generating ABLDuck documentation (11.5+ method)

BUILD FAILED
C:\devarea\psc-github\ablapidoc\build.xml:51: java.lang.NullPointerException: Cannot invoke "eu.rssw.rcode.GetSetModifier.toString()" because "property.setModifier" is null
	at za.co.mip.ablduck.ABLDuckClassVisitor.getGetSetAccessComment(ABLDuckClassVisitor.java:256)
	at za.co.mip.ablduck.ABLDuckClassVisitor.readProperty(ABLDuckClassVisitor.java:278)
	at za.co.mip.ablduck.ABLDuckClassVisitor.getCompilationUnit(ABLDuckClassVisitor.java:140)
	at za.co.mip.ablduck.ABLDuck.execute(ABLDuck.java:277)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
````

**Comment by PeterJudgeZA** [comment]
AST and AST-DEPENDENCIES attached as zip files. Rename to .jar for testing.
[ast.zip](https://github.com/Riverside-Software/pct/files/8500103/ast.zip)
[ast-dependencies.zip](https://github.com/Riverside-Software/pct/files/8500104/ast-dependencies.zip)

**Comment by gquerret** [comment]
Regression in documentation task introduced in AST.jar 12.5 (works in 12.4 and before).
You can try this version: https://ci.rssw.eu/job/PCT/job/bugfix%252FPCT-479/lastSuccessfulBuild/artifact/dist/PCT.jar

**Comment by PeterJudgeZA** [comment]
That works for me - ABLDuck runs to completion and produced HTML as expected.

Is it a regression in the OE side?

**Comment by gquerret** [comment]
I'd say it's a bug in the 12.5 API, as the modifier of the `set` property is said to be null while it should be `private`. And it worked up to 12.4.
Workaround is in master branch.
