### ISSUE TITLE
Error During ClassDocumentation

### ISSUE THREAD

**Issue by ezazwar1** [Riverside-Software/pct#495]
I am using 11.7.9, I went by the book, I added the TaskDef, copied the ast.jar and ast-dependecies.jar into ant home and i defined the classdocumentation as follows

 ```
<ClassDocumentation destDir="${Output.PreprocessOutput.Dir}" dlcHome="${dlc_home}">
  <fileset dir="${Output.Preprocess.Dir}" includes="**/*.cls" />
  <propath path="${Output.Preprocess.Dir}" />
</ClassDocumentation>
```

The Output Fails with below Error

[ClassDocumentation] Generating XML documentation (11.5+ method)
```
BUILD FAILED
C:\Agent\_work\1\s\build.xml:279: java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:444)
	at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:33)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:98)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:54)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:132)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:62)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:425)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:273)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:297)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:286)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:409)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at eu.rssw.rcode.ClassCompilationUnit.classToXML(ClassCompilationUnit.java:82)
	at eu.rssw.pct.oedoc.ClassDocumentationVisitor.toXML(ClassDocumentationVisitor.java:102)
	at eu.rssw.pct.oedoc.OpenEdgeDocumentation115.execute(OpenEdgeDocumentation115.java:157)
```

**Comment by ezazwar1** [comment]
I added the Activation.jar file in ANT_Home and now the build was successful
